// Code generated by protoc-gen-go.
// source: control_message.proto
// DO NOT EDIT!

/*
Package cmd is a generated protocol buffer package.

It is generated from these files:
	control_message.proto

It has these top-level messages:
	ControlMessage
	NetChan
	ComputeResource
	StartRequest
	InstructionSet
	Instruction
	ScatterPartitions
	RoundRobin
	CollectPartitions
	LocalSort
	MergeSortedTo
	OrderBy
	JoinPartitionedSorted
	CoGroupPartitionedSorted
	PipeAsArgs
	Script
	InputSplitReader
	DatasetShard
	DatasetShardLocation
	StartResponse
	StopRequest
	StopResponse
	GetStatusRequest
	ChannelStatus
	GetStatusResponse
	DeleteDatasetShardRequest
	DeleteDatasetShardResponse
	LocalStatusReportRequest
	LocalStatusReportResponse
	WriteRequest
	ReadRequest
*/
package cmd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ControlMessage struct {
	WriteRequest               *WriteRequest               `protobuf:"bytes,1,opt,name=writeRequest" json:"writeRequest,omitempty"`
	StartRequest               *StartRequest               `protobuf:"bytes,2,opt,name=startRequest" json:"startRequest,omitempty"`
	StartResponse              *StartResponse              `protobuf:"bytes,3,opt,name=startResponse" json:"startResponse,omitempty"`
	StopRequest                *StopRequest                `protobuf:"bytes,4,opt,name=stopRequest" json:"stopRequest,omitempty"`
	StopResponse               *StopResponse               `protobuf:"bytes,5,opt,name=stopResponse" json:"stopResponse,omitempty"`
	GetStatusRequest           *GetStatusRequest           `protobuf:"bytes,6,opt,name=getStatusRequest" json:"getStatusRequest,omitempty"`
	GetStatusResponse          *GetStatusResponse          `protobuf:"bytes,7,opt,name=getStatusResponse" json:"getStatusResponse,omitempty"`
	DeleteDatasetShardRequest  *DeleteDatasetShardRequest  `protobuf:"bytes,8,opt,name=deleteDatasetShardRequest" json:"deleteDatasetShardRequest,omitempty"`
	DeleteDatasetShardResponse *DeleteDatasetShardResponse `protobuf:"bytes,9,opt,name=deleteDatasetShardResponse" json:"deleteDatasetShardResponse,omitempty"`
	LocalStatusReportRequest   *LocalStatusReportRequest   `protobuf:"bytes,10,opt,name=localStatusReportRequest" json:"localStatusReportRequest,omitempty"`
	LocalStatusReportResponse  *LocalStatusReportResponse  `protobuf:"bytes,11,opt,name=localStatusReportResponse" json:"localStatusReportResponse,omitempty"`
	ReadRequest                *ReadRequest                `protobuf:"bytes,12,opt,name=readRequest" json:"readRequest,omitempty"`
	XXX_unrecognized           []byte                      `json:"-"`
}

func (m *ControlMessage) Reset()                    { *m = ControlMessage{} }
func (m *ControlMessage) String() string            { return proto.CompactTextString(m) }
func (*ControlMessage) ProtoMessage()               {}
func (*ControlMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ControlMessage) GetWriteRequest() *WriteRequest {
	if m != nil {
		return m.WriteRequest
	}
	return nil
}

func (m *ControlMessage) GetStartRequest() *StartRequest {
	if m != nil {
		return m.StartRequest
	}
	return nil
}

func (m *ControlMessage) GetStartResponse() *StartResponse {
	if m != nil {
		return m.StartResponse
	}
	return nil
}

func (m *ControlMessage) GetStopRequest() *StopRequest {
	if m != nil {
		return m.StopRequest
	}
	return nil
}

func (m *ControlMessage) GetStopResponse() *StopResponse {
	if m != nil {
		return m.StopResponse
	}
	return nil
}

func (m *ControlMessage) GetGetStatusRequest() *GetStatusRequest {
	if m != nil {
		return m.GetStatusRequest
	}
	return nil
}

func (m *ControlMessage) GetGetStatusResponse() *GetStatusResponse {
	if m != nil {
		return m.GetStatusResponse
	}
	return nil
}

func (m *ControlMessage) GetDeleteDatasetShardRequest() *DeleteDatasetShardRequest {
	if m != nil {
		return m.DeleteDatasetShardRequest
	}
	return nil
}

func (m *ControlMessage) GetDeleteDatasetShardResponse() *DeleteDatasetShardResponse {
	if m != nil {
		return m.DeleteDatasetShardResponse
	}
	return nil
}

func (m *ControlMessage) GetLocalStatusReportRequest() *LocalStatusReportRequest {
	if m != nil {
		return m.LocalStatusReportRequest
	}
	return nil
}

func (m *ControlMessage) GetLocalStatusReportResponse() *LocalStatusReportResponse {
	if m != nil {
		return m.LocalStatusReportResponse
	}
	return nil
}

func (m *ControlMessage) GetReadRequest() *ReadRequest {
	if m != nil {
		return m.ReadRequest
	}
	return nil
}

type NetChan struct {
	Server           *string `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	Port             *int32  `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NetChan) Reset()                    { *m = NetChan{} }
func (m *NetChan) String() string            { return proto.CompactTextString(m) }
func (*NetChan) ProtoMessage()               {}
func (*NetChan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NetChan) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *NetChan) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type ComputeResource struct {
	CpuCount         *int32 `protobuf:"varint,1,req,name=cpuCount" json:"cpuCount,omitempty"`
	CpuLevel         *int32 `protobuf:"varint,2,req,name=cpuLevel" json:"cpuLevel,omitempty"`
	GpuCount         *int32 `protobuf:"varint,3,req,name=gpuCount" json:"gpuCount,omitempty"`
	GpuLevel         *int32 `protobuf:"varint,4,req,name=gpuLevel" json:"gpuLevel,omitempty"`
	Memory           *int32 `protobuf:"varint,5,req,name=memory" json:"memory,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ComputeResource) Reset()                    { *m = ComputeResource{} }
func (m *ComputeResource) String() string            { return proto.CompactTextString(m) }
func (*ComputeResource) ProtoMessage()               {}
func (*ComputeResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ComputeResource) GetCpuCount() int32 {
	if m != nil && m.CpuCount != nil {
		return *m.CpuCount
	}
	return 0
}

func (m *ComputeResource) GetCpuLevel() int32 {
	if m != nil && m.CpuLevel != nil {
		return *m.CpuLevel
	}
	return 0
}

func (m *ComputeResource) GetGpuCount() int32 {
	if m != nil && m.GpuCount != nil {
		return *m.GpuCount
	}
	return 0
}

func (m *ComputeResource) GetGpuLevel() int32 {
	if m != nil && m.GpuLevel != nil {
		return *m.GpuLevel
	}
	return 0
}

func (m *ComputeResource) GetMemory() int32 {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return 0
}

type StartRequest struct {
	Instructions     *InstructionSet  `protobuf:"bytes,1,req,name=instructions" json:"instructions,omitempty"`
	Files            []string         `protobuf:"bytes,2,rep,name=files" json:"files,omitempty"`
	Dir              *string          `protobuf:"bytes,3,req,name=dir" json:"dir,omitempty"`
	Resource         *ComputeResource `protobuf:"bytes,4,req,name=resource" json:"resource,omitempty"`
	Host             *string          `protobuf:"bytes,5,req,name=host" json:"host,omitempty"`
	Port             *int32           `protobuf:"varint,6,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StartRequest) GetInstructions() *InstructionSet {
	if m != nil {
		return m.Instructions
	}
	return nil
}

func (m *StartRequest) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *StartRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *StartRequest) GetResource() *ComputeResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *StartRequest) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *StartRequest) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type InstructionSet struct {
	Instructions     []*Instruction `protobuf:"bytes,1,rep,name=instructions" json:"instructions,omitempty"`
	ReaderCount      *int32         `protobuf:"varint,2,req,name=readerCount" json:"readerCount,omitempty"`
	FlowHashCode     *uint32        `protobuf:"varint,3,opt,name=flowHashCode" json:"flowHashCode,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *InstructionSet) Reset()                    { *m = InstructionSet{} }
func (m *InstructionSet) String() string            { return proto.CompactTextString(m) }
func (*InstructionSet) ProtoMessage()               {}
func (*InstructionSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InstructionSet) GetInstructions() []*Instruction {
	if m != nil {
		return m.Instructions
	}
	return nil
}

func (m *InstructionSet) GetReaderCount() int32 {
	if m != nil && m.ReaderCount != nil {
		return *m.ReaderCount
	}
	return 0
}

func (m *InstructionSet) GetFlowHashCode() uint32 {
	if m != nil && m.FlowHashCode != nil {
		return *m.FlowHashCode
	}
	return 0
}

type Instruction struct {
	Name                     *string                   `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Script                   *Script                   `protobuf:"bytes,2,opt,name=script" json:"script,omitempty"`
	LocalSort                *LocalSort                `protobuf:"bytes,3,opt,name=localSort" json:"localSort,omitempty"`
	MergeSortedTo            *MergeSortedTo            `protobuf:"bytes,4,opt,name=mergeSortedTo" json:"mergeSortedTo,omitempty"`
	JoinPartitionedSorted    *JoinPartitionedSorted    `protobuf:"bytes,5,opt,name=joinPartitionedSorted" json:"joinPartitionedSorted,omitempty"`
	CoGroupPartitionedSorted *CoGroupPartitionedSorted `protobuf:"bytes,6,opt,name=coGroupPartitionedSorted" json:"coGroupPartitionedSorted,omitempty"`
	PipeAsArgs               *PipeAsArgs               `protobuf:"bytes,7,opt,name=pipeAsArgs" json:"pipeAsArgs,omitempty"`
	ScatterPartitions        *ScatterPartitions        `protobuf:"bytes,8,opt,name=scatterPartitions" json:"scatterPartitions,omitempty"`
	CollectPartitions        *CollectPartitions        `protobuf:"bytes,9,opt,name=collectPartitions" json:"collectPartitions,omitempty"`
	InputSplitReader         *InputSplitReader         `protobuf:"bytes,10,opt,name=inputSplitReader" json:"inputSplitReader,omitempty"`
	RoundRobin               *RoundRobin               `protobuf:"bytes,11,opt,name=roundRobin" json:"roundRobin,omitempty"`
	XXX_unrecognized         []byte                    `json:"-"`
}

func (m *Instruction) Reset()                    { *m = Instruction{} }
func (m *Instruction) String() string            { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()               {}
func (*Instruction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Instruction) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Instruction) GetScript() *Script {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *Instruction) GetLocalSort() *LocalSort {
	if m != nil {
		return m.LocalSort
	}
	return nil
}

func (m *Instruction) GetMergeSortedTo() *MergeSortedTo {
	if m != nil {
		return m.MergeSortedTo
	}
	return nil
}

func (m *Instruction) GetJoinPartitionedSorted() *JoinPartitionedSorted {
	if m != nil {
		return m.JoinPartitionedSorted
	}
	return nil
}

func (m *Instruction) GetCoGroupPartitionedSorted() *CoGroupPartitionedSorted {
	if m != nil {
		return m.CoGroupPartitionedSorted
	}
	return nil
}

func (m *Instruction) GetPipeAsArgs() *PipeAsArgs {
	if m != nil {
		return m.PipeAsArgs
	}
	return nil
}

func (m *Instruction) GetScatterPartitions() *ScatterPartitions {
	if m != nil {
		return m.ScatterPartitions
	}
	return nil
}

func (m *Instruction) GetCollectPartitions() *CollectPartitions {
	if m != nil {
		return m.CollectPartitions
	}
	return nil
}

func (m *Instruction) GetInputSplitReader() *InputSplitReader {
	if m != nil {
		return m.InputSplitReader
	}
	return nil
}

func (m *Instruction) GetRoundRobin() *RoundRobin {
	if m != nil {
		return m.RoundRobin
	}
	return nil
}

type ScatterPartitions struct {
	InputShardLocation   *DatasetShardLocation   `protobuf:"bytes,1,req,name=inputShardLocation" json:"inputShardLocation,omitempty"`
	OutputShardLocations []*DatasetShardLocation `protobuf:"bytes,2,rep,name=OutputShardLocations,json=outputShardLocations" json:"OutputShardLocations,omitempty"`
	ShardCount           *int32                  `protobuf:"varint,3,req,name=shardCount" json:"shardCount,omitempty"`
	Indexes              []int32                 `protobuf:"varint,4,rep,name=indexes" json:"indexes,omitempty"`
	XXX_unrecognized     []byte                  `json:"-"`
}

func (m *ScatterPartitions) Reset()                    { *m = ScatterPartitions{} }
func (m *ScatterPartitions) String() string            { return proto.CompactTextString(m) }
func (*ScatterPartitions) ProtoMessage()               {}
func (*ScatterPartitions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ScatterPartitions) GetInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.InputShardLocation
	}
	return nil
}

func (m *ScatterPartitions) GetOutputShardLocations() []*DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocations
	}
	return nil
}

func (m *ScatterPartitions) GetShardCount() int32 {
	if m != nil && m.ShardCount != nil {
		return *m.ShardCount
	}
	return 0
}

func (m *ScatterPartitions) GetIndexes() []int32 {
	if m != nil {
		return m.Indexes
	}
	return nil
}

type RoundRobin struct {
	InputShardLocation   *DatasetShardLocation   `protobuf:"bytes,1,req,name=inputShardLocation" json:"inputShardLocation,omitempty"`
	OutputShardLocations []*DatasetShardLocation `protobuf:"bytes,2,rep,name=OutputShardLocations,json=outputShardLocations" json:"OutputShardLocations,omitempty"`
	ShardCount           *int32                  `protobuf:"varint,3,req,name=shardCount" json:"shardCount,omitempty"`
	XXX_unrecognized     []byte                  `json:"-"`
}

func (m *RoundRobin) Reset()                    { *m = RoundRobin{} }
func (m *RoundRobin) String() string            { return proto.CompactTextString(m) }
func (*RoundRobin) ProtoMessage()               {}
func (*RoundRobin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RoundRobin) GetInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.InputShardLocation
	}
	return nil
}

func (m *RoundRobin) GetOutputShardLocations() []*DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocations
	}
	return nil
}

func (m *RoundRobin) GetShardCount() int32 {
	if m != nil && m.ShardCount != nil {
		return *m.ShardCount
	}
	return 0
}

type CollectPartitions struct {
	InputShardLocations []*DatasetShardLocation `protobuf:"bytes,1,rep,name=inputShardLocations" json:"inputShardLocations,omitempty"`
	OutputShardLocation *DatasetShardLocation   `protobuf:"bytes,2,req,name=outputShardLocation" json:"outputShardLocation,omitempty"`
	XXX_unrecognized    []byte                  `json:"-"`
}

func (m *CollectPartitions) Reset()                    { *m = CollectPartitions{} }
func (m *CollectPartitions) String() string            { return proto.CompactTextString(m) }
func (*CollectPartitions) ProtoMessage()               {}
func (*CollectPartitions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CollectPartitions) GetInputShardLocations() []*DatasetShardLocation {
	if m != nil {
		return m.InputShardLocations
	}
	return nil
}

func (m *CollectPartitions) GetOutputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocation
	}
	return nil
}

type LocalSort struct {
	InputShardLocation  *DatasetShardLocation `protobuf:"bytes,1,req,name=inputShardLocation" json:"inputShardLocation,omitempty"`
	OutputShardLocation *DatasetShardLocation `protobuf:"bytes,2,req,name=outputShardLocation" json:"outputShardLocation,omitempty"`
	OrderBys            []*OrderBy            `protobuf:"bytes,3,rep,name=orderBys" json:"orderBys,omitempty"`
	XXX_unrecognized    []byte                `json:"-"`
}

func (m *LocalSort) Reset()                    { *m = LocalSort{} }
func (m *LocalSort) String() string            { return proto.CompactTextString(m) }
func (*LocalSort) ProtoMessage()               {}
func (*LocalSort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LocalSort) GetInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.InputShardLocation
	}
	return nil
}

func (m *LocalSort) GetOutputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocation
	}
	return nil
}

func (m *LocalSort) GetOrderBys() []*OrderBy {
	if m != nil {
		return m.OrderBys
	}
	return nil
}

type MergeSortedTo struct {
	InputShardLocations []*DatasetShardLocation `protobuf:"bytes,1,rep,name=inputShardLocations" json:"inputShardLocations,omitempty"`
	OutputShardLocation *DatasetShardLocation   `protobuf:"bytes,2,req,name=outputShardLocation" json:"outputShardLocation,omitempty"`
	OrderBys            []*OrderBy              `protobuf:"bytes,3,rep,name=orderBys" json:"orderBys,omitempty"`
	XXX_unrecognized    []byte                  `json:"-"`
}

func (m *MergeSortedTo) Reset()                    { *m = MergeSortedTo{} }
func (m *MergeSortedTo) String() string            { return proto.CompactTextString(m) }
func (*MergeSortedTo) ProtoMessage()               {}
func (*MergeSortedTo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MergeSortedTo) GetInputShardLocations() []*DatasetShardLocation {
	if m != nil {
		return m.InputShardLocations
	}
	return nil
}

func (m *MergeSortedTo) GetOutputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocation
	}
	return nil
}

func (m *MergeSortedTo) GetOrderBys() []*OrderBy {
	if m != nil {
		return m.OrderBys
	}
	return nil
}

type OrderBy struct {
	Index            *int32 `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	Order            *int32 `protobuf:"varint,2,req,name=order" json:"order,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OrderBy) Reset()                    { *m = OrderBy{} }
func (m *OrderBy) String() string            { return proto.CompactTextString(m) }
func (*OrderBy) ProtoMessage()               {}
func (*OrderBy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *OrderBy) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *OrderBy) GetOrder() int32 {
	if m != nil && m.Order != nil {
		return *m.Order
	}
	return 0
}

type JoinPartitionedSorted struct {
	LeftInputShardLocation  *DatasetShardLocation `protobuf:"bytes,1,req,name=leftInputShardLocation" json:"leftInputShardLocation,omitempty"`
	RightInputShardLocation *DatasetShardLocation `protobuf:"bytes,2,req,name=rightInputShardLocation" json:"rightInputShardLocation,omitempty"`
	Indexes                 []int32               `protobuf:"varint,3,rep,name=indexes" json:"indexes,omitempty"`
	IsLeftOuterJoin         *bool                 `protobuf:"varint,4,req,name=isLeftOuterJoin" json:"isLeftOuterJoin,omitempty"`
	IsRightOuterJoin        *bool                 `protobuf:"varint,5,req,name=isRightOuterJoin" json:"isRightOuterJoin,omitempty"`
	OutputShardLocation     *DatasetShardLocation `protobuf:"bytes,6,req,name=outputShardLocation" json:"outputShardLocation,omitempty"`
	XXX_unrecognized        []byte                `json:"-"`
}

func (m *JoinPartitionedSorted) Reset()                    { *m = JoinPartitionedSorted{} }
func (m *JoinPartitionedSorted) String() string            { return proto.CompactTextString(m) }
func (*JoinPartitionedSorted) ProtoMessage()               {}
func (*JoinPartitionedSorted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *JoinPartitionedSorted) GetLeftInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.LeftInputShardLocation
	}
	return nil
}

func (m *JoinPartitionedSorted) GetRightInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.RightInputShardLocation
	}
	return nil
}

func (m *JoinPartitionedSorted) GetIndexes() []int32 {
	if m != nil {
		return m.Indexes
	}
	return nil
}

func (m *JoinPartitionedSorted) GetIsLeftOuterJoin() bool {
	if m != nil && m.IsLeftOuterJoin != nil {
		return *m.IsLeftOuterJoin
	}
	return false
}

func (m *JoinPartitionedSorted) GetIsRightOuterJoin() bool {
	if m != nil && m.IsRightOuterJoin != nil {
		return *m.IsRightOuterJoin
	}
	return false
}

func (m *JoinPartitionedSorted) GetOutputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocation
	}
	return nil
}

type CoGroupPartitionedSorted struct {
	LeftInputShardLocation  *DatasetShardLocation `protobuf:"bytes,1,req,name=leftInputShardLocation" json:"leftInputShardLocation,omitempty"`
	RightInputShardLocation *DatasetShardLocation `protobuf:"bytes,2,req,name=rightInputShardLocation" json:"rightInputShardLocation,omitempty"`
	OutputShardLocation     *DatasetShardLocation `protobuf:"bytes,3,req,name=outputShardLocation" json:"outputShardLocation,omitempty"`
	Indexes                 []int32               `protobuf:"varint,4,rep,name=indexes" json:"indexes,omitempty"`
	XXX_unrecognized        []byte                `json:"-"`
}

func (m *CoGroupPartitionedSorted) Reset()                    { *m = CoGroupPartitionedSorted{} }
func (m *CoGroupPartitionedSorted) String() string            { return proto.CompactTextString(m) }
func (*CoGroupPartitionedSorted) ProtoMessage()               {}
func (*CoGroupPartitionedSorted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CoGroupPartitionedSorted) GetLeftInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.LeftInputShardLocation
	}
	return nil
}

func (m *CoGroupPartitionedSorted) GetRightInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.RightInputShardLocation
	}
	return nil
}

func (m *CoGroupPartitionedSorted) GetOutputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocation
	}
	return nil
}

func (m *CoGroupPartitionedSorted) GetIndexes() []int32 {
	if m != nil {
		return m.Indexes
	}
	return nil
}

type PipeAsArgs struct {
	InputShardLocation  *DatasetShardLocation `protobuf:"bytes,1,req,name=inputShardLocation" json:"inputShardLocation,omitempty"`
	OutputShardLocation *DatasetShardLocation `protobuf:"bytes,2,req,name=outputShardLocation" json:"outputShardLocation,omitempty"`
	Code                *string               `protobuf:"bytes,3,req,name=code" json:"code,omitempty"`
	XXX_unrecognized    []byte                `json:"-"`
}

func (m *PipeAsArgs) Reset()                    { *m = PipeAsArgs{} }
func (m *PipeAsArgs) String() string            { return proto.CompactTextString(m) }
func (*PipeAsArgs) ProtoMessage()               {}
func (*PipeAsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PipeAsArgs) GetInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.InputShardLocation
	}
	return nil
}

func (m *PipeAsArgs) GetOutputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocation
	}
	return nil
}

func (m *PipeAsArgs) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

type Script struct {
	InputShardLocation  *DatasetShardLocation `protobuf:"bytes,1,req,name=inputShardLocation" json:"inputShardLocation,omitempty"`
	OutputShardLocation *DatasetShardLocation `protobuf:"bytes,2,req,name=outputShardLocation" json:"outputShardLocation,omitempty"`
	IsPipe              *bool                 `protobuf:"varint,3,req,name=isPipe" json:"isPipe,omitempty"`
	Path                *string               `protobuf:"bytes,4,req,name=path" json:"path,omitempty"`
	Args                []string              `protobuf:"bytes,5,rep,name=args" json:"args,omitempty"`
	Env                 []string              `protobuf:"bytes,6,rep,name=env" json:"env,omitempty"`
	XXX_unrecognized    []byte                `json:"-"`
}

func (m *Script) Reset()                    { *m = Script{} }
func (m *Script) String() string            { return proto.CompactTextString(m) }
func (*Script) ProtoMessage()               {}
func (*Script) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Script) GetInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.InputShardLocation
	}
	return nil
}

func (m *Script) GetOutputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocation
	}
	return nil
}

func (m *Script) GetIsPipe() bool {
	if m != nil && m.IsPipe != nil {
		return *m.IsPipe
	}
	return false
}

func (m *Script) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Script) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Script) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

type InputSplitReader struct {
	InputShardLocation  *DatasetShardLocation `protobuf:"bytes,1,req,name=inputShardLocation" json:"inputShardLocation,omitempty"`
	OutputShardLocation *DatasetShardLocation `protobuf:"bytes,2,req,name=outputShardLocation" json:"outputShardLocation,omitempty"`
	InputType           *string               `protobuf:"bytes,3,req,name=inputType" json:"inputType,omitempty"`
	XXX_unrecognized    []byte                `json:"-"`
}

func (m *InputSplitReader) Reset()                    { *m = InputSplitReader{} }
func (m *InputSplitReader) String() string            { return proto.CompactTextString(m) }
func (*InputSplitReader) ProtoMessage()               {}
func (*InputSplitReader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *InputSplitReader) GetInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.InputShardLocation
	}
	return nil
}

func (m *InputSplitReader) GetOutputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocation
	}
	return nil
}

func (m *InputSplitReader) GetInputType() string {
	if m != nil && m.InputType != nil {
		return *m.InputType
	}
	return ""
}

type DatasetShard struct {
	FlowName         *string `protobuf:"bytes,1,req,name=FlowName,json=flowName" json:"FlowName,omitempty"`
	DatasetId        *int32  `protobuf:"varint,2,req,name=DatasetId,json=datasetId" json:"DatasetId,omitempty"`
	DatasetShardId   *int32  `protobuf:"varint,3,req,name=DatasetShardId,json=datasetShardId" json:"DatasetShardId,omitempty"`
	FlowHashCode     *uint32 `protobuf:"varint,4,opt,name=FlowHashCode,json=flowHashCode" json:"FlowHashCode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DatasetShard) Reset()                    { *m = DatasetShard{} }
func (m *DatasetShard) String() string            { return proto.CompactTextString(m) }
func (*DatasetShard) ProtoMessage()               {}
func (*DatasetShard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DatasetShard) GetFlowName() string {
	if m != nil && m.FlowName != nil {
		return *m.FlowName
	}
	return ""
}

func (m *DatasetShard) GetDatasetId() int32 {
	if m != nil && m.DatasetId != nil {
		return *m.DatasetId
	}
	return 0
}

func (m *DatasetShard) GetDatasetShardId() int32 {
	if m != nil && m.DatasetShardId != nil {
		return *m.DatasetShardId
	}
	return 0
}

func (m *DatasetShard) GetFlowHashCode() uint32 {
	if m != nil && m.FlowHashCode != nil {
		return *m.FlowHashCode
	}
	return 0
}

type DatasetShardLocation struct {
	Shard            *DatasetShard `protobuf:"bytes,1,req,name=shard" json:"shard,omitempty"`
	Host             *string       `protobuf:"bytes,2,req,name=Host,json=host" json:"Host,omitempty"`
	Port             *int32        `protobuf:"varint,3,req,name=Port,json=port" json:"Port,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *DatasetShardLocation) Reset()                    { *m = DatasetShardLocation{} }
func (m *DatasetShardLocation) String() string            { return proto.CompactTextString(m) }
func (*DatasetShardLocation) ProtoMessage()               {}
func (*DatasetShardLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DatasetShardLocation) GetShard() *DatasetShard {
	if m != nil {
		return m.Shard
	}
	return nil
}

func (m *DatasetShardLocation) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *DatasetShardLocation) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type StartResponse struct {
	Pid              *int32     `protobuf:"varint,1,req,name=pid" json:"pid,omitempty"`
	Error            *string    `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Stderr           *NetChan   `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
	Outputs          []*NetChan `protobuf:"bytes,4,rep,name=outputs" json:"outputs,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *StartResponse) Reset()                    { *m = StartResponse{} }
func (m *StartResponse) String() string            { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()               {}
func (*StartResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *StartResponse) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *StartResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *StartResponse) GetStderr() *NetChan {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *StartResponse) GetOutputs() []*NetChan {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type StopRequest struct {
	StartRequestHash *uint32 `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *StopRequest) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

type StopResponse struct {
	StartRequestHash *uint32 `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StopResponse) Reset()                    { *m = StopResponse{} }
func (m *StopResponse) String() string            { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()               {}
func (*StopResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *StopResponse) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

func (m *StopResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type GetStatusRequest struct {
	StartRequestHash *uint32 `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetStatusRequest) Reset()                    { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()               {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GetStatusRequest) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

type ChannelStatus struct {
	Length           *int64  `protobuf:"varint,1,req,name=length" json:"length,omitempty"`
	StartTime        *int64  `protobuf:"varint,2,opt,name=startTime" json:"startTime,omitempty"`
	StopTime         *int64  `protobuf:"varint,3,opt,name=stopTime" json:"stopTime,omitempty"`
	Name             *string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChannelStatus) Reset()                    { *m = ChannelStatus{} }
func (m *ChannelStatus) String() string            { return proto.CompactTextString(m) }
func (*ChannelStatus) ProtoMessage()               {}
func (*ChannelStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ChannelStatus) GetLength() int64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *ChannelStatus) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *ChannelStatus) GetStopTime() int64 {
	if m != nil && m.StopTime != nil {
		return *m.StopTime
	}
	return 0
}

func (m *ChannelStatus) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type GetStatusResponse struct {
	StartRequestHash *uint32          `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            *string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	InputStatuses    []*ChannelStatus `protobuf:"bytes,3,rep,name=inputStatuses" json:"inputStatuses,omitempty"`
	OutputStatuses   []*ChannelStatus `protobuf:"bytes,4,rep,name=outputStatuses" json:"outputStatuses,omitempty"`
	RequestTime      *int64           `protobuf:"varint,5,opt,name=requestTime" json:"requestTime,omitempty"`
	StartTime        *int64           `protobuf:"varint,6,opt,name=startTime" json:"startTime,omitempty"`
	StopTime         *int64           `protobuf:"varint,7,opt,name=stopTime" json:"stopTime,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetStatusResponse) Reset()                    { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()               {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GetStatusResponse) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

func (m *GetStatusResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *GetStatusResponse) GetInputStatuses() []*ChannelStatus {
	if m != nil {
		return m.InputStatuses
	}
	return nil
}

func (m *GetStatusResponse) GetOutputStatuses() []*ChannelStatus {
	if m != nil {
		return m.OutputStatuses
	}
	return nil
}

func (m *GetStatusResponse) GetRequestTime() int64 {
	if m != nil && m.RequestTime != nil {
		return *m.RequestTime
	}
	return 0
}

func (m *GetStatusResponse) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *GetStatusResponse) GetStopTime() int64 {
	if m != nil && m.StopTime != nil {
		return *m.StopTime
	}
	return 0
}

type DeleteDatasetShardRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteDatasetShardRequest) Reset()                    { *m = DeleteDatasetShardRequest{} }
func (m *DeleteDatasetShardRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDatasetShardRequest) ProtoMessage()               {}
func (*DeleteDatasetShardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *DeleteDatasetShardRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type DeleteDatasetShardResponse struct {
	Error            *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteDatasetShardResponse) Reset()                    { *m = DeleteDatasetShardResponse{} }
func (m *DeleteDatasetShardResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDatasetShardResponse) ProtoMessage()               {}
func (*DeleteDatasetShardResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *DeleteDatasetShardResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type LocalStatusReportRequest struct {
	StartRequestHash *uint32          `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            *string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	InputStatuses    []*ChannelStatus `protobuf:"bytes,3,rep,name=inputStatuses" json:"inputStatuses,omitempty"`
	OutputStatuses   []*ChannelStatus `protobuf:"bytes,4,rep,name=outputStatuses" json:"outputStatuses,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *LocalStatusReportRequest) Reset()                    { *m = LocalStatusReportRequest{} }
func (m *LocalStatusReportRequest) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusReportRequest) ProtoMessage()               {}
func (*LocalStatusReportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *LocalStatusReportRequest) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

func (m *LocalStatusReportRequest) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *LocalStatusReportRequest) GetInputStatuses() []*ChannelStatus {
	if m != nil {
		return m.InputStatuses
	}
	return nil
}

func (m *LocalStatusReportRequest) GetOutputStatuses() []*ChannelStatus {
	if m != nil {
		return m.OutputStatuses
	}
	return nil
}

type LocalStatusReportResponse struct {
	Error            *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LocalStatusReportResponse) Reset()                    { *m = LocalStatusReportResponse{} }
func (m *LocalStatusReportResponse) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusReportResponse) ProtoMessage()               {}
func (*LocalStatusReportResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *LocalStatusReportResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type WriteRequest struct {
	ChannelName      *string `protobuf:"bytes,1,req,name=channelName" json:"channelName,omitempty"`
	WriterName       *string `protobuf:"bytes,2,req,name=writerName" json:"writerName,omitempty"`
	ReaderCount      *int32  `protobuf:"varint,3,req,name=readerCount" json:"readerCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *WriteRequest) GetChannelName() string {
	if m != nil && m.ChannelName != nil {
		return *m.ChannelName
	}
	return ""
}

func (m *WriteRequest) GetWriterName() string {
	if m != nil && m.WriterName != nil {
		return *m.WriterName
	}
	return ""
}

func (m *WriteRequest) GetReaderCount() int32 {
	if m != nil && m.ReaderCount != nil {
		return *m.ReaderCount
	}
	return 0
}

type ReadRequest struct {
	ChannelName      *string `protobuf:"bytes,1,req,name=channelName" json:"channelName,omitempty"`
	ReaderName       *string `protobuf:"bytes,2,req,name=readerName" json:"readerName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ReadRequest) GetChannelName() string {
	if m != nil && m.ChannelName != nil {
		return *m.ChannelName
	}
	return ""
}

func (m *ReadRequest) GetReaderName() string {
	if m != nil && m.ReaderName != nil {
		return *m.ReaderName
	}
	return ""
}

func init() {
	proto.RegisterType((*ControlMessage)(nil), "cmd.ControlMessage")
	proto.RegisterType((*NetChan)(nil), "cmd.NetChan")
	proto.RegisterType((*ComputeResource)(nil), "cmd.ComputeResource")
	proto.RegisterType((*StartRequest)(nil), "cmd.StartRequest")
	proto.RegisterType((*InstructionSet)(nil), "cmd.InstructionSet")
	proto.RegisterType((*Instruction)(nil), "cmd.Instruction")
	proto.RegisterType((*ScatterPartitions)(nil), "cmd.ScatterPartitions")
	proto.RegisterType((*RoundRobin)(nil), "cmd.RoundRobin")
	proto.RegisterType((*CollectPartitions)(nil), "cmd.CollectPartitions")
	proto.RegisterType((*LocalSort)(nil), "cmd.LocalSort")
	proto.RegisterType((*MergeSortedTo)(nil), "cmd.MergeSortedTo")
	proto.RegisterType((*OrderBy)(nil), "cmd.OrderBy")
	proto.RegisterType((*JoinPartitionedSorted)(nil), "cmd.JoinPartitionedSorted")
	proto.RegisterType((*CoGroupPartitionedSorted)(nil), "cmd.CoGroupPartitionedSorted")
	proto.RegisterType((*PipeAsArgs)(nil), "cmd.PipeAsArgs")
	proto.RegisterType((*Script)(nil), "cmd.Script")
	proto.RegisterType((*InputSplitReader)(nil), "cmd.InputSplitReader")
	proto.RegisterType((*DatasetShard)(nil), "cmd.DatasetShard")
	proto.RegisterType((*DatasetShardLocation)(nil), "cmd.DatasetShardLocation")
	proto.RegisterType((*StartResponse)(nil), "cmd.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "cmd.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "cmd.StopResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "cmd.GetStatusRequest")
	proto.RegisterType((*ChannelStatus)(nil), "cmd.ChannelStatus")
	proto.RegisterType((*GetStatusResponse)(nil), "cmd.GetStatusResponse")
	proto.RegisterType((*DeleteDatasetShardRequest)(nil), "cmd.DeleteDatasetShardRequest")
	proto.RegisterType((*DeleteDatasetShardResponse)(nil), "cmd.DeleteDatasetShardResponse")
	proto.RegisterType((*LocalStatusReportRequest)(nil), "cmd.LocalStatusReportRequest")
	proto.RegisterType((*LocalStatusReportResponse)(nil), "cmd.LocalStatusReportResponse")
	proto.RegisterType((*WriteRequest)(nil), "cmd.WriteRequest")
	proto.RegisterType((*ReadRequest)(nil), "cmd.ReadRequest")
}

func init() { proto.RegisterFile("control_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x58, 0xcd, 0x6e, 0x1d, 0xb5,
	0x17, 0xd7, 0xdc, 0xaf, 0xe4, 0x9e, 0x7b, 0x93, 0x26, 0x6e, 0x92, 0xff, 0x4d, 0xf4, 0xa7, 0x44,
	0x03, 0x2a, 0x11, 0x42, 0x2d, 0x44, 0x54, 0x7c, 0x2c, 0x90, 0x4a, 0xaa, 0xb6, 0x81, 0xb4, 0x09,
	0x4e, 0x25, 0x84, 0x84, 0x54, 0x0d, 0x33, 0xce, 0xcd, 0xa0, 0x7b, 0xc7, 0x83, 0xed, 0xdb, 0xd2,
	0x07, 0x60, 0xd7, 0x25, 0x1b, 0x9e, 0x00, 0xb1, 0x60, 0xcf, 0x13, 0x20, 0x58, 0xb0, 0x81, 0x0d,
	0x6f, 0xc0, 0x9e, 0x35, 0x0b, 0xe4, 0x63, 0xcf, 0x8c, 0xe7, 0xce, 0x4c, 0xa0, 0xa5, 0x8b, 0x74,
	0x67, 0x9f, 0x2f, 0x1f, 0x1f, 0x1f, 0xff, 0xec, 0x73, 0x60, 0x3d, 0xe4, 0x89, 0x12, 0x7c, 0x72,
	0x7f, 0xca, 0xa4, 0x0c, 0xc6, 0xec, 0x4a, 0x2a, 0xb8, 0xe2, 0xa4, 0x1d, 0x4e, 0x23, 0xff, 0xf7,
	0x1e, 0x2c, 0xef, 0x19, 0xf6, 0x1d, 0xc3, 0x25, 0xd7, 0x60, 0xf8, 0x50, 0xc4, 0x8a, 0x51, 0xf6,
	0xc5, 0x8c, 0x49, 0x35, 0xf2, 0xb6, 0xbd, 0x9d, 0xc1, 0xee, 0xea, 0x95, 0x70, 0x1a, 0x5d, 0xf9,
	0xd8, 0x61, 0xd0, 0x92, 0x98, 0x56, 0x93, 0x2a, 0x10, 0x2a, 0x53, 0x6b, 0x39, 0x6a, 0xc7, 0x0e,
	0x83, 0x96, 0xc4, 0xc8, 0xdb, 0xb0, 0x64, 0xe7, 0x32, 0xe5, 0x89, 0x64, 0xa3, 0x36, 0xea, 0x11,
	0x57, 0xcf, 0x70, 0x68, 0x59, 0x90, 0xec, 0xc2, 0x40, 0x2a, 0x9e, 0x66, 0xeb, 0x75, 0x50, 0x6f,
	0xc5, 0xea, 0xe5, 0x74, 0xea, 0x0a, 0x19, 0x27, 0xf5, 0xd4, 0x2e, 0xd6, 0x2d, 0x39, 0x59, 0x30,
	0x68, 0x49, 0x8c, 0x5c, 0x87, 0x95, 0x31, 0x53, 0xc7, 0x2a, 0x50, 0x33, 0x99, 0xad, 0xd7, 0x43,
	0xd5, 0x75, 0x54, 0xbd, 0x35, 0xc7, 0xa4, 0x15, 0x71, 0x72, 0x03, 0x56, 0x1d, 0x9a, 0x5d, 0x7e,
	0x01, 0x6d, 0x6c, 0xcc, 0xdb, 0xb0, 0x3e, 0x54, 0x15, 0xc8, 0xa7, 0xb0, 0x19, 0xb1, 0x09, 0x53,
	0xec, 0x46, 0xa0, 0x02, 0xc9, 0xd4, 0xf1, 0x69, 0x20, 0xa2, 0xcc, 0xa3, 0x45, 0xb4, 0x76, 0x09,
	0xad, 0xdd, 0x68, 0x92, 0xa2, 0xcd, 0x06, 0xc8, 0x7d, 0xd8, 0xaa, 0x63, 0x5a, 0x67, 0xfb, 0x68,
	0xfe, 0xc5, 0x46, 0xf3, 0xd6, 0xeb, 0x33, 0x4c, 0x90, 0x4f, 0x60, 0x34, 0xe1, 0x61, 0x30, 0xc9,
	0x76, 0x95, 0xf2, 0x22, 0x5f, 0x00, 0xcd, 0xbf, 0x80, 0xe6, 0x0f, 0x1a, 0x84, 0x68, 0xa3, 0xba,
	0x8e, 0x4c, 0x0d, 0xcf, 0xba, 0x3e, 0x70, 0x22, 0x73, 0xd0, 0x24, 0x45, 0x9b, 0x0d, 0xe8, 0x5c,
	0x13, 0x2c, 0xc8, 0x23, 0x3d, 0x74, 0x72, 0x8d, 0x16, 0x74, 0xea, 0x0a, 0xf9, 0xd7, 0x60, 0xe1,
	0x2e, 0x53, 0x7b, 0xa7, 0x41, 0x42, 0x36, 0xa0, 0x27, 0x99, 0x78, 0xc0, 0xc4, 0xc8, 0xdb, 0x6e,
	0xed, 0xf4, 0xa9, 0x9d, 0x11, 0x02, 0x1d, 0xbd, 0xcc, 0xa8, 0xb5, 0xdd, 0xda, 0xe9, 0x52, 0x1c,
	0xfb, 0xdf, 0x78, 0x70, 0x61, 0x8f, 0x4f, 0xd3, 0x99, 0xbe, 0x5a, 0x92, 0xcf, 0x44, 0xc8, 0xc8,
	0x16, 0x2c, 0x86, 0xe9, 0x6c, 0x8f, 0xcf, 0x12, 0x85, 0x16, 0xba, 0x34, 0x9f, 0x5b, 0xde, 0x01,
	0x7b, 0xc0, 0x26, 0xd6, 0x4e, 0x3e, 0xd7, 0xbc, 0x71, 0xa6, 0xd7, 0x36, 0xbc, 0xb1, 0xa3, 0x37,
	0xce, 0xf4, 0x3a, 0x39, 0xcf, 0xe8, 0x6d, 0x40, 0x6f, 0xca, 0xa6, 0x5c, 0x3c, 0x1a, 0x75, 0x91,
	0x63, 0x67, 0xfe, 0xcf, 0x1e, 0x0c, 0xdd, 0xbb, 0x4c, 0xde, 0x82, 0x61, 0x9c, 0x48, 0x25, 0x66,
	0xa1, 0x8a, 0x79, 0x22, 0xd1, 0xb9, 0xc1, 0xee, 0x45, 0x0c, 0xcc, 0x7e, 0xc1, 0x38, 0x66, 0x8a,
	0x96, 0x04, 0xc9, 0x1a, 0x74, 0x4f, 0xe2, 0x09, 0x93, 0xa3, 0xd6, 0x76, 0x7b, 0xa7, 0x4f, 0xcd,
	0x84, 0xac, 0x40, 0x3b, 0x8a, 0x05, 0xba, 0xda, 0xa7, 0x7a, 0x48, 0x5e, 0x87, 0x45, 0x61, 0xa3,
	0x80, 0x5e, 0x0e, 0x76, 0xd7, 0xd0, 0xf8, 0x5c, 0x84, 0x68, 0x2e, 0xa5, 0x63, 0x7a, 0xca, 0xa5,
	0x42, 0xcf, 0xfb, 0x14, 0xc7, 0x79, 0x9c, 0x7b, 0x4e, 0x9c, 0x1f, 0x7b, 0xb0, 0x5c, 0x76, 0x91,
	0xbc, 0x59, 0xd9, 0x4d, 0x3b, 0x3f, 0x66, 0x47, 0x74, 0x6e, 0x2b, 0xdb, 0x26, 0x37, 0x98, 0x30,
	0x71, 0x36, 0x67, 0xe0, 0x92, 0x88, 0x0f, 0xc3, 0x93, 0x09, 0x7f, 0x78, 0x3b, 0x90, 0xa7, 0x7b,
	0x3c, 0x32, 0x10, 0xb7, 0x44, 0x4b, 0x34, 0xff, 0x71, 0x17, 0x06, 0xce, 0x1a, 0xda, 0xe5, 0x24,
	0x98, 0x32, 0x9b, 0x30, 0x38, 0x26, 0x2f, 0x41, 0x4f, 0x86, 0x22, 0x4e, 0x33, 0x70, 0x1d, 0x18,
	0xdc, 0x42, 0x12, 0xb5, 0x2c, 0xf2, 0x1a, 0xf4, 0x4d, 0x1e, 0xeb, 0x0d, 0x1b, 0x30, 0x5d, 0x76,
	0x12, 0x5f, 0x67, 0x75, 0x21, 0xa0, 0xe1, 0x77, 0xca, 0xc4, 0x98, 0xe9, 0x09, 0x8b, 0xee, 0x71,
	0x0b, 0xa3, 0x06, 0x7e, 0xef, 0xb8, 0x1c, 0x5a, 0x16, 0x24, 0x47, 0xb0, 0xfe, 0x39, 0x8f, 0x93,
	0xa3, 0x40, 0xa8, 0x58, 0x7b, 0xcc, 0x22, 0xc3, 0xb2, 0x98, 0xba, 0x85, 0x16, 0x3e, 0xa8, 0x93,
	0xa0, 0xf5, 0x8a, 0x1a, 0x1d, 0x42, 0x7e, 0x4b, 0xf0, 0x59, 0x5a, 0x35, 0xda, 0x73, 0xd0, 0x61,
	0xaf, 0x41, 0x88, 0x36, 0xaa, 0x93, 0xab, 0x00, 0x69, 0x9c, 0xb2, 0xeb, 0xf2, 0xba, 0x18, 0x4b,
	0x0b, 0xbb, 0x17, 0xd0, 0xd8, 0x51, 0x4e, 0xa6, 0x8e, 0x88, 0x86, 0x6b, 0x19, 0x06, 0x4a, 0x31,
	0x91, 0x1b, 0x93, 0x16, 0x60, 0x37, 0x6c, 0xd4, 0xe7, 0xb8, 0xb4, 0xaa, 0xa0, 0xad, 0x84, 0x7c,
	0x32, 0x61, 0xa1, 0x72, 0xac, 0xf4, 0x1d, 0x2b, 0x7b, 0xf3, 0x5c, 0x5a, 0x55, 0xd0, 0xaf, 0x4f,
	0x9c, 0xa4, 0x33, 0x75, 0x9c, 0x4e, 0x62, 0x45, 0x31, 0xaf, 0x2c, 0x5a, 0xae, 0xdb, 0xd4, 0x2c,
	0x33, 0x69, 0x45, 0x5c, 0xef, 0x5f, 0xf0, 0x59, 0x12, 0x51, 0xfe, 0x59, 0x9c, 0x58, 0x38, 0x34,
	0xfb, 0xa7, 0x39, 0x99, 0x3a, 0x22, 0xfe, 0x1f, 0x1e, 0xac, 0x56, 0xb6, 0x48, 0xf6, 0x81, 0x18,
	0xd3, 0x1a, 0xd5, 0x75, 0x3e, 0x69, 0xb2, 0xbd, 0xf4, 0x9b, 0xe6, 0x61, 0x70, 0x60, 0x3f, 0x13,
	0xa0, 0x35, 0x4a, 0xe4, 0x0e, 0xac, 0x1d, 0xce, 0xd4, 0x3c, 0xd9, 0xe0, 0xc1, 0x99, 0xc6, 0xd6,
	0x78, 0x8d, 0x1a, 0xb9, 0x04, 0x20, 0x35, 0xc5, 0xc5, 0x3a, 0x87, 0x42, 0x46, 0xb0, 0x10, 0x27,
	0x11, 0xfb, 0x92, 0xc9, 0x51, 0x67, 0xbb, 0xbd, 0xd3, 0xa5, 0xd9, 0xd4, 0xff, 0xd1, 0x03, 0x28,
	0x82, 0xf0, 0xfc, 0x6e, 0xd1, 0xff, 0xde, 0x83, 0xd5, 0x4a, 0x3e, 0x91, 0x0f, 0xe1, 0x62, 0xd5,
	0xb5, 0x0c, 0xda, 0xce, 0xf0, 0xa1, 0x4e, 0x4b, 0x1b, 0xab, 0x71, 0x0d, 0x21, 0xef, 0x6c, 0x63,
	0x35, 0x5a, 0xfe, 0x2f, 0x1e, 0xf4, 0x73, 0x4c, 0x7a, 0x96, 0x71, 0x7f, 0x96, 0x5e, 0x92, 0x1d,
	0x58, 0xe4, 0x22, 0x62, 0xe2, 0xfd, 0x47, 0x72, 0xd4, 0xc6, 0xa0, 0x0d, 0xd1, 0xc2, 0xa1, 0x21,
	0xd2, 0x9c, 0xeb, 0xff, 0xe6, 0xc1, 0x52, 0x09, 0x31, 0xcf, 0x6f, 0xec, 0x9f, 0x60, 0x57, 0xd7,
	0x60, 0xc1, 0x12, 0xf5, 0x9b, 0x8d, 0x97, 0xc6, 0x7e, 0x41, 0xcc, 0x44, 0x53, 0x51, 0xd8, 0x3e,
	0x7c, 0x66, 0xe2, 0xff, 0xd5, 0x82, 0xf5, 0x5a, 0xf0, 0x27, 0x1f, 0xc1, 0xc6, 0x84, 0x9d, 0xa8,
	0xfd, 0xa7, 0x38, 0xec, 0x06, 0x45, 0x72, 0x0c, 0xff, 0x13, 0xf1, 0xf8, 0xb4, 0xce, 0xe6, 0x3f,
	0x86, 0xa7, 0x49, 0xd3, 0x45, 0x8c, 0x76, 0x09, 0x31, 0xc8, 0x0e, 0x5c, 0x88, 0xe5, 0x01, 0x3b,
	0x51, 0x87, 0x33, 0xc5, 0x84, 0xde, 0x25, 0x7e, 0x4d, 0x16, 0xe9, 0x3c, 0x99, 0xbc, 0x0a, 0x2b,
	0xb1, 0xa4, 0x7a, 0x81, 0x42, 0xb4, 0x8b, 0xa2, 0x15, 0x7a, 0xd3, 0xf9, 0xf6, 0x9e, 0xea, 0x6e,
	0x7d, 0xd7, 0x82, 0x51, 0xd3, 0x33, 0xf9, 0xdc, 0x9c, 0x40, 0x43, 0x44, 0xda, 0x4f, 0x95, 0xf1,
	0xcd, 0x0f, 0xc0, 0x0f, 0x1e, 0x40, 0xf1, 0x0b, 0x38, 0xb7, 0x40, 0x44, 0xa0, 0x13, 0x9a, 0xcf,
	0x23, 0x7e, 0x08, 0xf5, 0xd8, 0xff, 0xd3, 0x83, 0x9e, 0xf9, 0xfe, 0x9d, 0x5b, 0xb7, 0x37, 0xa0,
	0x17, 0x4b, 0x1d, 0x5e, 0x74, 0x7c, 0x91, 0xda, 0x19, 0x7e, 0xc9, 0x03, 0x75, 0x8a, 0x37, 0xa7,
	0x4f, 0x71, 0xac, 0x69, 0x81, 0xfe, 0x9f, 0x75, 0xb1, 0x26, 0xc0, 0xb1, 0x2e, 0x09, 0x58, 0xf2,
	0x60, 0xd4, 0x43, 0x92, 0x1e, 0xfa, 0x3f, 0x79, 0xb0, 0x32, 0xff, 0xe5, 0x39, 0xb7, 0xdb, 0xff,
	0x3f, 0xf4, 0x71, 0x89, 0x7b, 0x8f, 0xd2, 0xec, 0xe8, 0x0a, 0x82, 0xff, 0xb5, 0x07, 0x43, 0xd7,
	0x96, 0x2e, 0xca, 0x6e, 0x4e, 0xf8, 0xc3, 0xbb, 0xc5, 0xcf, 0x7f, 0xf1, 0xc4, 0xce, 0xb5, 0x29,
	0x2b, 0xbb, 0x1f, 0x59, 0xb0, 0xed, 0x47, 0x19, 0x81, 0x5c, 0x86, 0x65, 0xd7, 0xd2, 0x7e, 0x64,
	0x7f, 0x08, 0xcb, 0x51, 0x89, 0xaa, 0x6b, 0x91, 0x9b, 0x6e, 0x2d, 0xd2, 0xa9, 0xa9, 0x45, 0xc6,
	0xb0, 0x56, 0xb7, 0x43, 0xf2, 0x0a, 0x74, 0xf1, 0xbf, 0x61, 0xe3, 0xba, 0x5a, 0x89, 0x05, 0x35,
	0x7c, 0x7d, 0x90, 0xb7, 0xb9, 0x34, 0xb5, 0x90, 0x53, 0x83, 0x1d, 0x99, 0x92, 0xa4, 0xa8, 0xc1,
	0xbe, 0xf2, 0x60, 0xa9, 0xd4, 0xe3, 0xd1, 0xc7, 0x9d, 0xc6, 0x91, 0x7d, 0x61, 0xf4, 0x50, 0xbf,
	0x2f, 0x4c, 0x08, 0x2e, 0xb0, 0xe6, 0xe9, 0x53, 0x33, 0x21, 0x2f, 0x43, 0x4f, 0xaa, 0x88, 0x09,
	0x61, 0x4b, 0x1c, 0xf3, 0x7c, 0xd9, 0x7a, 0x9b, 0x5a, 0x1e, 0xb9, 0x0c, 0x0b, 0xe6, 0x50, 0xcc,
	0xa5, 0x9f, 0x17, 0xcb, 0x98, 0xfe, 0x3b, 0x30, 0x70, 0x5a, 0x46, 0x1a, 0xb6, 0xdd, 0x1e, 0x95,
	0x8e, 0x0b, 0x7a, 0xb4, 0x44, 0x2b, 0x74, 0xff, 0x48, 0x57, 0xc4, 0x4e, 0xab, 0xe8, 0x09, 0x74,
	0xeb, 0xb7, 0xe6, 0xbf, 0x07, 0x2b, 0xf3, 0xfd, 0xa4, 0x27, 0xf2, 0x68, 0x06, 0x4b, 0x7a, 0x77,
	0x09, 0xb3, 0xad, 0x0c, 0x7d, 0x05, 0x27, 0x2c, 0x19, 0x2b, 0xa3, 0xd2, 0xa6, 0x76, 0xa6, 0x13,
	0x0a, 0x95, 0xef, 0xc5, 0x53, 0x86, 0x2e, 0xb4, 0x69, 0x41, 0xd0, 0xa9, 0x28, 0x15, 0x4f, 0x91,
	0xd9, 0x46, 0x66, 0x3e, 0xcf, 0x8b, 0xd3, 0x0e, 0xfa, 0x8d, 0x63, 0xff, 0xdb, 0x16, 0xac, 0x56,
	0x7a, 0x58, 0xff, 0x3d, 0x1c, 0xba, 0x42, 0x35, 0x97, 0x14, 0x0d, 0xb3, 0xec, 0xbf, 0x62, 0x2a,
	0xd4, 0xd2, 0x46, 0x69, 0x59, 0x90, 0xbc, 0x0b, 0xcb, 0xf6, 0x4a, 0x66, 0xaa, 0x9d, 0x46, 0xd5,
	0x39, 0x49, 0x53, 0xd4, 0xa3, 0x6b, 0x18, 0x80, 0x2e, 0x06, 0xc0, 0x25, 0x95, 0xa3, 0xd7, 0x3b,
	0x2b, 0x7a, 0x0b, 0xe5, 0xe8, 0xf9, 0x57, 0x61, 0xb3, 0xb1, 0x3d, 0x57, 0x57, 0xf7, 0xfb, 0xbb,
	0xb0, 0xd5, 0xdc, 0x70, 0x2b, 0xc2, 0xe6, 0xb9, 0x59, 0xf4, 0xab, 0x07, 0xa3, 0xa6, 0x36, 0xda,
	0xf3, 0x7a, 0x2a, 0xfe, 0x1b, 0xb0, 0xd9, 0xd8, 0xbe, 0x6b, 0x88, 0x83, 0x80, 0xa1, 0xdb, 0xb4,
	0xd6, 0x07, 0x1b, 0x9a, 0x35, 0x1c, 0x90, 0x75, 0x49, 0xba, 0xce, 0xc2, 0xc6, 0xb6, 0x40, 0x01,
	0x03, 0x61, 0x0e, 0x65, 0xbe, 0xdf, 0xd3, 0xae, 0xf4, 0x7b, 0xfc, 0x43, 0x18, 0x38, 0x5d, 0xc1,
	0x7f, 0xb7, 0xa4, 0xd1, 0x77, 0x97, 0x2c, 0x28, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x07, 0x53,
	0xc7, 0xcb, 0xc2, 0x17, 0x00, 0x00,
}
