// Code generated by protoc-gen-go.
// source: control_message.proto
// DO NOT EDIT!

/*
Package cmd is a generated protocol buffer package.

It is generated from these files:
	control_message.proto
	execution_instruction.proto

It has these top-level messages:
	ControlMessage
	NetChan
	ComputeResource
	StartRequest
	StartResponse
	StopRequest
	StopResponse
	GetStatusRequest
	ChannelStatus
	GetStatusResponse
	DeleteDatasetShardRequest
	DeleteDatasetShardResponse
	LocalStatusReportRequest
	LocalStatusReportResponse
	WriteRequest
	ReadRequest
	InstructionSet
	Instruction
	ScatterPartitions
	CollectPartitions
	LocalSort
	MergeSortedTo
	JoinPartitionedSorted
	CoGroupPartitionedSorted
	Script
	DatasetShard
	DatasetShardLocation
*/
package cmd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ControlMessage_Type int32

const (
	ControlMessage_NoOp                       ControlMessage_Type = 1
	ControlMessage_StartRequest               ControlMessage_Type = 2
	ControlMessage_StartResponse              ControlMessage_Type = 3
	ControlMessage_StopRequest                ControlMessage_Type = 4
	ControlMessage_StopResponse               ControlMessage_Type = 5
	ControlMessage_GetStatusRequest           ControlMessage_Type = 6
	ControlMessage_GetStatusResponse          ControlMessage_Type = 7
	ControlMessage_DeleteDatasetShardRequest  ControlMessage_Type = 8
	ControlMessage_DeleteDatasetShardResponse ControlMessage_Type = 9
	ControlMessage_LocalStatusReportRequest   ControlMessage_Type = 10
	ControlMessage_LocalStatusReportResponse  ControlMessage_Type = 11
	ControlMessage_ReadRequest                ControlMessage_Type = 12
	ControlMessage_WriteRequest               ControlMessage_Type = 13
)

var ControlMessage_Type_name = map[int32]string{
	1:  "NoOp",
	2:  "StartRequest",
	3:  "StartResponse",
	4:  "StopRequest",
	5:  "StopResponse",
	6:  "GetStatusRequest",
	7:  "GetStatusResponse",
	8:  "DeleteDatasetShardRequest",
	9:  "DeleteDatasetShardResponse",
	10: "LocalStatusReportRequest",
	11: "LocalStatusReportResponse",
	12: "ReadRequest",
	13: "WriteRequest",
}
var ControlMessage_Type_value = map[string]int32{
	"NoOp":                       1,
	"StartRequest":               2,
	"StartResponse":              3,
	"StopRequest":                4,
	"StopResponse":               5,
	"GetStatusRequest":           6,
	"GetStatusResponse":          7,
	"DeleteDatasetShardRequest":  8,
	"DeleteDatasetShardResponse": 9,
	"LocalStatusReportRequest":   10,
	"LocalStatusReportResponse":  11,
	"ReadRequest":                12,
	"WriteRequest":               13,
}

func (x ControlMessage_Type) Enum() *ControlMessage_Type {
	p := new(ControlMessage_Type)
	*p = x
	return p
}
func (x ControlMessage_Type) String() string {
	return proto.EnumName(ControlMessage_Type_name, int32(x))
}
func (x *ControlMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ControlMessage_Type_value, data, "ControlMessage_Type")
	if err != nil {
		return err
	}
	*x = ControlMessage_Type(value)
	return nil
}
func (ControlMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ControlMessage struct {
	Type                       *ControlMessage_Type        `protobuf:"varint,1,req,name=type,enum=cmd.ControlMessage_Type" json:"type,omitempty"`
	StartRequest               *StartRequest               `protobuf:"bytes,2,opt,name=startRequest" json:"startRequest,omitempty"`
	StartResponse              *StartResponse              `protobuf:"bytes,3,opt,name=startResponse" json:"startResponse,omitempty"`
	StopRequest                *StopRequest                `protobuf:"bytes,4,opt,name=stopRequest" json:"stopRequest,omitempty"`
	StopResponse               *StopResponse               `protobuf:"bytes,5,opt,name=stopResponse" json:"stopResponse,omitempty"`
	GetStatusRequest           *GetStatusRequest           `protobuf:"bytes,6,opt,name=getStatusRequest" json:"getStatusRequest,omitempty"`
	GetStatusResponse          *GetStatusResponse          `protobuf:"bytes,7,opt,name=getStatusResponse" json:"getStatusResponse,omitempty"`
	DeleteDatasetShardRequest  *DeleteDatasetShardRequest  `protobuf:"bytes,8,opt,name=deleteDatasetShardRequest" json:"deleteDatasetShardRequest,omitempty"`
	DeleteDatasetShardResponse *DeleteDatasetShardResponse `protobuf:"bytes,9,opt,name=deleteDatasetShardResponse" json:"deleteDatasetShardResponse,omitempty"`
	LocalStatusReportRequest   *LocalStatusReportRequest   `protobuf:"bytes,10,opt,name=localStatusReportRequest" json:"localStatusReportRequest,omitempty"`
	LocalStatusReportResponse  *LocalStatusReportResponse  `protobuf:"bytes,11,opt,name=localStatusReportResponse" json:"localStatusReportResponse,omitempty"`
	ReadRequest                *ReadRequest                `protobuf:"bytes,12,opt,name=readRequest" json:"readRequest,omitempty"`
	WriteRequest               *WriteRequest               `protobuf:"bytes,13,opt,name=writeRequest" json:"writeRequest,omitempty"`
	XXX_unrecognized           []byte                      `json:"-"`
}

func (m *ControlMessage) Reset()                    { *m = ControlMessage{} }
func (m *ControlMessage) String() string            { return proto.CompactTextString(m) }
func (*ControlMessage) ProtoMessage()               {}
func (*ControlMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ControlMessage) GetType() ControlMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ControlMessage_NoOp
}

func (m *ControlMessage) GetStartRequest() *StartRequest {
	if m != nil {
		return m.StartRequest
	}
	return nil
}

func (m *ControlMessage) GetStartResponse() *StartResponse {
	if m != nil {
		return m.StartResponse
	}
	return nil
}

func (m *ControlMessage) GetStopRequest() *StopRequest {
	if m != nil {
		return m.StopRequest
	}
	return nil
}

func (m *ControlMessage) GetStopResponse() *StopResponse {
	if m != nil {
		return m.StopResponse
	}
	return nil
}

func (m *ControlMessage) GetGetStatusRequest() *GetStatusRequest {
	if m != nil {
		return m.GetStatusRequest
	}
	return nil
}

func (m *ControlMessage) GetGetStatusResponse() *GetStatusResponse {
	if m != nil {
		return m.GetStatusResponse
	}
	return nil
}

func (m *ControlMessage) GetDeleteDatasetShardRequest() *DeleteDatasetShardRequest {
	if m != nil {
		return m.DeleteDatasetShardRequest
	}
	return nil
}

func (m *ControlMessage) GetDeleteDatasetShardResponse() *DeleteDatasetShardResponse {
	if m != nil {
		return m.DeleteDatasetShardResponse
	}
	return nil
}

func (m *ControlMessage) GetLocalStatusReportRequest() *LocalStatusReportRequest {
	if m != nil {
		return m.LocalStatusReportRequest
	}
	return nil
}

func (m *ControlMessage) GetLocalStatusReportResponse() *LocalStatusReportResponse {
	if m != nil {
		return m.LocalStatusReportResponse
	}
	return nil
}

func (m *ControlMessage) GetReadRequest() *ReadRequest {
	if m != nil {
		return m.ReadRequest
	}
	return nil
}

func (m *ControlMessage) GetWriteRequest() *WriteRequest {
	if m != nil {
		return m.WriteRequest
	}
	return nil
}

type NetChan struct {
	Server           *string `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	Port             *int32  `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NetChan) Reset()                    { *m = NetChan{} }
func (m *NetChan) String() string            { return proto.CompactTextString(m) }
func (*NetChan) ProtoMessage()               {}
func (*NetChan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NetChan) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *NetChan) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type ComputeResource struct {
	CpuCount         *int32 `protobuf:"varint,1,req,name=cpuCount" json:"cpuCount,omitempty"`
	CpuLevel         *int32 `protobuf:"varint,2,req,name=cpuLevel" json:"cpuLevel,omitempty"`
	Memory           *int32 `protobuf:"varint,3,req,name=memory" json:"memory,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ComputeResource) Reset()                    { *m = ComputeResource{} }
func (m *ComputeResource) String() string            { return proto.CompactTextString(m) }
func (*ComputeResource) ProtoMessage()               {}
func (*ComputeResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ComputeResource) GetCpuCount() int32 {
	if m != nil && m.CpuCount != nil {
		return *m.CpuCount
	}
	return 0
}

func (m *ComputeResource) GetCpuLevel() int32 {
	if m != nil && m.CpuLevel != nil {
		return *m.CpuLevel
	}
	return 0
}

func (m *ComputeResource) GetMemory() int32 {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return 0
}

type StartRequest struct {
	Path             *string          `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Args             []string         `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	Envs             []string         `protobuf:"bytes,3,rep,name=envs" json:"envs,omitempty"`
	Dir              *string          `protobuf:"bytes,4,req,name=dir" json:"dir,omitempty"`
	Resource         *ComputeResource `protobuf:"bytes,5,req,name=resource" json:"resource,omitempty"`
	HashCode         *uint32          `protobuf:"varint,6,req,name=hashCode" json:"hashCode,omitempty"`
	Host             *string          `protobuf:"bytes,7,opt,name=host" json:"host,omitempty"`
	Port             *int32           `protobuf:"varint,8,opt,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StartRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *StartRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *StartRequest) GetEnvs() []string {
	if m != nil {
		return m.Envs
	}
	return nil
}

func (m *StartRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *StartRequest) GetResource() *ComputeResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *StartRequest) GetHashCode() uint32 {
	if m != nil && m.HashCode != nil {
		return *m.HashCode
	}
	return 0
}

func (m *StartRequest) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *StartRequest) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type StartResponse struct {
	Pid              *int32     `protobuf:"varint,1,req,name=pid" json:"pid,omitempty"`
	Error            *string    `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Stderr           *NetChan   `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
	Outputs          []*NetChan `protobuf:"bytes,4,rep,name=outputs" json:"outputs,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *StartResponse) Reset()                    { *m = StartResponse{} }
func (m *StartResponse) String() string            { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()               {}
func (*StartResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StartResponse) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *StartResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *StartResponse) GetStderr() *NetChan {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *StartResponse) GetOutputs() []*NetChan {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type StopRequest struct {
	StartRequestHash *uint32 `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StopRequest) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

type StopResponse struct {
	StartRequestHash *uint32 `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StopResponse) Reset()                    { *m = StopResponse{} }
func (m *StopResponse) String() string            { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()               {}
func (*StopResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StopResponse) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

func (m *StopResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type GetStatusRequest struct {
	StartRequestHash *uint32 `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetStatusRequest) Reset()                    { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()               {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetStatusRequest) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

type ChannelStatus struct {
	Length           *int64  `protobuf:"varint,1,req,name=length" json:"length,omitempty"`
	StartTime        *int64  `protobuf:"varint,2,opt,name=startTime" json:"startTime,omitempty"`
	StopTime         *int64  `protobuf:"varint,3,opt,name=stopTime" json:"stopTime,omitempty"`
	Name             *string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChannelStatus) Reset()                    { *m = ChannelStatus{} }
func (m *ChannelStatus) String() string            { return proto.CompactTextString(m) }
func (*ChannelStatus) ProtoMessage()               {}
func (*ChannelStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ChannelStatus) GetLength() int64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *ChannelStatus) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *ChannelStatus) GetStopTime() int64 {
	if m != nil && m.StopTime != nil {
		return *m.StopTime
	}
	return 0
}

func (m *ChannelStatus) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type GetStatusResponse struct {
	StartRequestHash *uint32          `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            *string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	InputStatuses    []*ChannelStatus `protobuf:"bytes,3,rep,name=inputStatuses" json:"inputStatuses,omitempty"`
	OutputStatuses   []*ChannelStatus `protobuf:"bytes,4,rep,name=outputStatuses" json:"outputStatuses,omitempty"`
	RequestTime      *int64           `protobuf:"varint,5,opt,name=requestTime" json:"requestTime,omitempty"`
	StartTime        *int64           `protobuf:"varint,6,opt,name=startTime" json:"startTime,omitempty"`
	StopTime         *int64           `protobuf:"varint,7,opt,name=stopTime" json:"stopTime,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetStatusResponse) Reset()                    { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()               {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetStatusResponse) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

func (m *GetStatusResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *GetStatusResponse) GetInputStatuses() []*ChannelStatus {
	if m != nil {
		return m.InputStatuses
	}
	return nil
}

func (m *GetStatusResponse) GetOutputStatuses() []*ChannelStatus {
	if m != nil {
		return m.OutputStatuses
	}
	return nil
}

func (m *GetStatusResponse) GetRequestTime() int64 {
	if m != nil && m.RequestTime != nil {
		return *m.RequestTime
	}
	return 0
}

func (m *GetStatusResponse) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *GetStatusResponse) GetStopTime() int64 {
	if m != nil && m.StopTime != nil {
		return *m.StopTime
	}
	return 0
}

type DeleteDatasetShardRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteDatasetShardRequest) Reset()                    { *m = DeleteDatasetShardRequest{} }
func (m *DeleteDatasetShardRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDatasetShardRequest) ProtoMessage()               {}
func (*DeleteDatasetShardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteDatasetShardRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type DeleteDatasetShardResponse struct {
	Error            *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteDatasetShardResponse) Reset()                    { *m = DeleteDatasetShardResponse{} }
func (m *DeleteDatasetShardResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDatasetShardResponse) ProtoMessage()               {}
func (*DeleteDatasetShardResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeleteDatasetShardResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type LocalStatusReportRequest struct {
	StartRequestHash *uint32          `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            *string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	InputStatuses    []*ChannelStatus `protobuf:"bytes,3,rep,name=inputStatuses" json:"inputStatuses,omitempty"`
	OutputStatuses   []*ChannelStatus `protobuf:"bytes,4,rep,name=outputStatuses" json:"outputStatuses,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *LocalStatusReportRequest) Reset()                    { *m = LocalStatusReportRequest{} }
func (m *LocalStatusReportRequest) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusReportRequest) ProtoMessage()               {}
func (*LocalStatusReportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *LocalStatusReportRequest) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

func (m *LocalStatusReportRequest) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *LocalStatusReportRequest) GetInputStatuses() []*ChannelStatus {
	if m != nil {
		return m.InputStatuses
	}
	return nil
}

func (m *LocalStatusReportRequest) GetOutputStatuses() []*ChannelStatus {
	if m != nil {
		return m.OutputStatuses
	}
	return nil
}

type LocalStatusReportResponse struct {
	Error            *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LocalStatusReportResponse) Reset()                    { *m = LocalStatusReportResponse{} }
func (m *LocalStatusReportResponse) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusReportResponse) ProtoMessage()               {}
func (*LocalStatusReportResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *LocalStatusReportResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type WriteRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *WriteRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type ReadRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ReadRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ControlMessage)(nil), "cmd.ControlMessage")
	proto.RegisterType((*NetChan)(nil), "cmd.NetChan")
	proto.RegisterType((*ComputeResource)(nil), "cmd.ComputeResource")
	proto.RegisterType((*StartRequest)(nil), "cmd.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "cmd.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "cmd.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "cmd.StopResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "cmd.GetStatusRequest")
	proto.RegisterType((*ChannelStatus)(nil), "cmd.ChannelStatus")
	proto.RegisterType((*GetStatusResponse)(nil), "cmd.GetStatusResponse")
	proto.RegisterType((*DeleteDatasetShardRequest)(nil), "cmd.DeleteDatasetShardRequest")
	proto.RegisterType((*DeleteDatasetShardResponse)(nil), "cmd.DeleteDatasetShardResponse")
	proto.RegisterType((*LocalStatusReportRequest)(nil), "cmd.LocalStatusReportRequest")
	proto.RegisterType((*LocalStatusReportResponse)(nil), "cmd.LocalStatusReportResponse")
	proto.RegisterType((*WriteRequest)(nil), "cmd.WriteRequest")
	proto.RegisterType((*ReadRequest)(nil), "cmd.ReadRequest")
	proto.RegisterEnum("cmd.ControlMessage_Type", ControlMessage_Type_name, ControlMessage_Type_value)
}

func init() { proto.RegisterFile("control_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 884 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x55, 0xdd, 0x8a, 0x23, 0x45,
	0x14, 0x26, 0xdd, 0x9d, 0xbf, 0x93, 0x64, 0xb6, 0xe6, 0x30, 0xb3, 0xf4, 0x0e, 0xbb, 0x6b, 0x6c,
	0x44, 0x82, 0xc8, 0xa8, 0x81, 0x05, 0xf5, 0x42, 0x90, 0x0c, 0xe8, 0xc5, 0xb8, 0x4a, 0xcd, 0x82,
	0x08, 0xc2, 0xd2, 0x24, 0xc5, 0x24, 0x90, 0x74, 0xb5, 0x55, 0xd5, 0x23, 0xf3, 0x00, 0xbe, 0x89,
	0xe0, 0x95, 0x2f, 0xb3, 0x4f, 0x24, 0x75, 0xba, 0xd2, 0xe9, 0x4a, 0xd2, 0x81, 0xc5, 0xab, 0xbd,
	0xab, 0xf3, 0xf7, 0xd5, 0xa9, 0xaf, 0xbe, 0x3a, 0x05, 0x97, 0x73, 0x99, 0x19, 0x25, 0xd7, 0x6f,
	0x37, 0x42, 0xeb, 0xf4, 0x5e, 0x5c, 0xe7, 0x4a, 0x1a, 0x89, 0xe1, 0x7c, 0xb3, 0x48, 0xfe, 0xed,
	0xc3, 0xd9, 0xac, 0x0c, 0xff, 0x54, 0x46, 0xf1, 0x73, 0x88, 0xcc, 0x63, 0x2e, 0xe2, 0xd6, 0x38,
	0x98, 0x9c, 0x4d, 0xe3, 0xeb, 0xf9, 0x66, 0x71, 0xed, 0xa7, 0x5c, 0xbf, 0x79, 0xcc, 0x05, 0xa7,
	0x2c, 0x7c, 0x05, 0x43, 0x6d, 0x52, 0x65, 0xb8, 0xf8, 0xa3, 0x10, 0xda, 0xc4, 0xc1, 0xb8, 0x35,
	0x19, 0x4c, 0xcf, 0xa9, 0xea, 0xae, 0x16, 0xe0, 0x5e, 0x1a, 0x7e, 0x0d, 0x23, 0x67, 0xeb, 0x5c,
	0x66, 0x5a, 0xc4, 0x21, 0xd5, 0x61, 0xbd, 0xae, 0x8c, 0x70, 0x3f, 0x11, 0xa7, 0x30, 0xd0, 0x46,
	0xe6, 0xdb, 0xfd, 0x22, 0xaa, 0x63, 0xae, 0xae, 0xf2, 0xf3, 0x7a, 0x52, 0xd9, 0xa4, 0x35, 0xdd,
	0x66, 0x6d, 0xaf, 0xc9, 0x5d, 0x80, 0x7b, 0x69, 0xf8, 0x3d, 0xb0, 0x7b, 0x61, 0xee, 0x4c, 0x6a,
	0x0a, 0xbd, 0xdd, 0xaf, 0x43, 0xa5, 0x97, 0x54, 0xfa, 0xc3, 0x5e, 0x90, 0x1f, 0xa4, 0xe3, 0x0d,
	0x9c, 0xd7, 0x7c, 0x6e, 0xfb, 0x2e, 0x61, 0x3c, 0xdd, 0xc7, 0x70, 0x3d, 0x1c, 0x16, 0xe0, 0xef,
	0xf0, 0x6c, 0x21, 0xd6, 0xc2, 0x88, 0x9b, 0xd4, 0xa4, 0x5a, 0x98, 0xbb, 0x65, 0xaa, 0x16, 0xdb,
	0x8e, 0x7a, 0x84, 0xf6, 0x92, 0xd0, 0x6e, 0x9a, 0xb2, 0x78, 0x33, 0x00, 0xbe, 0x85, 0xab, 0x63,
	0x41, 0xd7, 0x6c, 0x9f, 0xe0, 0x3f, 0x6a, 0x84, 0x77, 0x5d, 0x9f, 0x80, 0xc0, 0xdf, 0x20, 0x5e,
	0xcb, 0x79, 0xba, 0xde, 0x9e, 0x2a, 0x97, 0x3b, 0xbd, 0x00, 0xc1, 0xbf, 0x20, 0xf8, 0xdb, 0x86,
	0x24, 0xde, 0x58, 0x6e, 0x99, 0x39, 0x12, 0x73, 0xad, 0x0f, 0x6a, 0xcc, 0xdc, 0x36, 0x65, 0xf1,
	0x66, 0x00, 0xab, 0x35, 0x25, 0xd2, 0x8a, 0xe9, 0x61, 0x4d, 0x6b, 0x7c, 0xe7, 0xe7, 0xf5, 0x24,
	0xab, 0xb5, 0x3f, 0xd5, 0xca, 0x88, 0x6d, 0xd1, 0xa8, 0xa6, 0xb5, 0x5f, 0x6b, 0x01, 0xee, 0xa5,
	0x25, 0x7f, 0x07, 0x10, 0xd9, 0x67, 0x85, 0x3d, 0x88, 0x5e, 0xcb, 0x9f, 0x73, 0xd6, 0x42, 0x06,
	0xc3, 0xfa, 0x0b, 0x62, 0x01, 0x9e, 0xc3, 0xc8, 0x7b, 0x1b, 0x2c, 0xc4, 0x27, 0x30, 0xa8, 0xc9,
	0x9e, 0x45, 0x65, 0xd5, 0x4e, 0xc4, 0xac, 0x8d, 0x17, 0xc0, 0xf6, 0x95, 0xca, 0x3a, 0x78, 0x09,
	0xe7, 0x07, 0xda, 0x63, 0x5d, 0x7c, 0x01, 0xcf, 0x1a, 0x45, 0xc4, 0x7a, 0xf8, 0x12, 0xae, 0x9a,
	0x45, 0xc0, 0xfa, 0xf8, 0x1c, 0xe2, 0xa6, 0x5b, 0x64, 0x60, 0xc1, 0x1b, 0xef, 0x81, 0x0d, 0xec,
	0x59, 0x6a, 0xb4, 0xb2, 0xa1, 0x3d, 0x4b, 0x9d, 0x32, 0x36, 0x4a, 0x5e, 0x41, 0xf7, 0xb5, 0x30,
	0xb3, 0x65, 0x9a, 0xe1, 0x53, 0xe8, 0x68, 0xa1, 0x1e, 0x84, 0xa2, 0x49, 0xd5, 0xe7, 0xce, 0x42,
	0x84, 0xc8, 0xe2, 0xc6, 0xc1, 0x38, 0x98, 0xb4, 0x39, 0xad, 0x93, 0x14, 0x9e, 0xcc, 0xe4, 0x26,
	0x2f, 0x2c, 0x94, 0x96, 0x85, 0x9a, 0x0b, 0xbc, 0x82, 0xde, 0x3c, 0x2f, 0x66, 0xb2, 0xc8, 0x0c,
	0x01, 0xb4, 0x79, 0x65, 0xbb, 0xd8, 0xad, 0x78, 0x10, 0x6b, 0x07, 0x53, 0xd9, 0x76, 0xdb, 0x8d,
	0xd8, 0x48, 0xf5, 0x18, 0x87, 0x14, 0x71, 0x56, 0xf2, 0xae, 0xe5, 0x5f, 0x17, 0xf5, 0x91, 0x9a,
	0xa5, 0xeb, 0x8e, 0xd6, 0xd6, 0x97, 0xaa, 0x7b, 0x1d, 0x07, 0xe3, 0xd0, 0xfa, 0xec, 0xda, 0xfa,
	0x44, 0xf6, 0xa0, 0xe3, 0xb0, 0xf4, 0xd9, 0x35, 0x32, 0x08, 0x17, 0x2b, 0x15, 0x47, 0x54, 0x6a,
	0x97, 0xf8, 0x25, 0xf4, 0x94, 0x6b, 0x3d, 0x6e, 0x8f, 0x83, 0xc9, 0x60, 0x7a, 0xe1, 0x26, 0xb3,
	0x77, 0x2c, 0x5e, 0x65, 0xd9, 0x43, 0x2c, 0x53, 0xbd, 0x9c, 0xc9, 0x85, 0x88, 0x3b, 0xe3, 0x60,
	0x32, 0xe2, 0x95, 0x6d, 0xf7, 0x5c, 0x4a, 0x6d, 0x68, 0x12, 0xf5, 0x39, 0xad, 0x2b, 0xde, 0xec,
	0x3c, 0xd9, 0xf2, 0xf6, 0x57, 0x6b, 0x4f, 0x71, 0xb6, 0xb3, 0x7c, 0xb5, 0x70, 0x8c, 0xd9, 0x25,
	0x5e, 0x40, 0x5b, 0x28, 0x25, 0x15, 0x8d, 0xfe, 0x3e, 0x2f, 0x0d, 0xfc, 0x04, 0x3a, 0xda, 0x2c,
	0x84, 0x52, 0x6e, 0xb2, 0x0f, 0xa9, 0x5b, 0x77, 0x77, 0xdc, 0xc5, 0xf0, 0x53, 0xe8, 0xca, 0xc2,
	0xe4, 0x85, 0xd1, 0x71, 0x34, 0x0e, 0x0f, 0xd2, 0xb6, 0xc1, 0xe4, 0x1b, 0x4f, 0xe5, 0xf8, 0x19,
	0xb0, 0xfa, 0x6f, 0xf2, 0x63, 0xaa, 0x4b, 0x9a, 0x47, 0xfc, 0xc0, 0x9f, 0xfc, 0xe2, 0xbf, 0x87,
	0xf7, 0xa9, 0x3d, 0x7e, 0xb4, 0xe4, 0xbb, 0xc3, 0xf7, 0xf4, 0x5e, 0x1d, 0x15, 0x30, 0xb2, 0xa7,
	0xcb, 0x84, 0x7b, 0x07, 0x56, 0x52, 0x6b, 0x91, 0xdd, 0x3b, 0xad, 0x84, 0xdc, 0x59, 0xf8, 0x1c,
	0xfa, 0x54, 0xfc, 0x66, 0xb5, 0x11, 0xd4, 0x42, 0xc8, 0x77, 0x0e, 0x7b, 0xbf, 0xf6, 0xb7, 0xa2,
	0x60, 0x48, 0xc1, 0xca, 0xb6, 0x77, 0x99, 0xa5, 0x1b, 0x41, 0xbf, 0x63, 0x9f, 0xd3, 0x3a, 0xf9,
	0x27, 0x38, 0xf2, 0xe2, 0xff, 0x3f, 0x1d, 0xf6, 0x2b, 0x5f, 0x65, 0x79, 0xe1, 0x80, 0x45, 0x29,
	0xe4, 0xed, 0x57, 0xee, 0x1d, 0x94, 0xfb, 0x89, 0xf8, 0x2d, 0x9c, 0x95, 0x17, 0x5c, 0x95, 0x46,
	0x8d, 0xa5, 0x7b, 0x99, 0x38, 0xb6, 0xa3, 0x99, 0x5a, 0x23, 0x02, 0xda, 0x44, 0x40, 0xdd, 0xe5,
	0xb3, 0xd7, 0x39, 0xc5, 0x5e, 0xd7, 0x67, 0x2f, 0xf9, 0xe2, 0xc4, 0x0c, 0xac, 0xa8, 0x75, 0xcf,
	0x9a, 0xa8, 0x9d, 0x9e, 0x9a, 0x8a, 0x3b, 0xda, 0x5a, 0x75, 0x15, 0xbd, 0x6b, 0x35, 0x8f, 0xca,
	0x0f, 0xf5, 0x56, 0x92, 0xaf, 0x4e, 0x0c, 0xf8, 0x06, 0x1e, 0x12, 0x7f, 0xc6, 0x1f, 0xe5, 0xf7,
	0x63, 0xef, 0x63, 0x38, 0x96, 0xf2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0x9b, 0x01, 0xea,
	0xe5, 0x0a, 0x00, 0x00,
}
