// Code generated by protoc-gen-go.
// source: control_message.proto
// DO NOT EDIT!

/*
Package cmd is a generated protocol buffer package.

It is generated from these files:
	control_message.proto

It has these top-level messages:
	ControlMessage
	NetChan
	ComputeResource
	StartRequest
	InstructionSet
	Instruction
	ScatterPartitions
	CollectPartitions
	LocalSort
	MergeSortedTo
	JoinPartitionedSorted
	CoGroupPartitionedSorted
	PipeAsArgs
	Script
	DatasetShard
	DatasetShardLocation
	StartResponse
	StopRequest
	StopResponse
	GetStatusRequest
	ChannelStatus
	GetStatusResponse
	DeleteDatasetShardRequest
	DeleteDatasetShardResponse
	LocalStatusReportRequest
	LocalStatusReportResponse
	WriteRequest
	ReadRequest
*/
package cmd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ControlMessage struct {
	WriteRequest               *WriteRequest               `protobuf:"bytes,1,opt,name=writeRequest" json:"writeRequest,omitempty"`
	StartRequest               *StartRequest               `protobuf:"bytes,2,opt,name=startRequest" json:"startRequest,omitempty"`
	StartResponse              *StartResponse              `protobuf:"bytes,3,opt,name=startResponse" json:"startResponse,omitempty"`
	StopRequest                *StopRequest                `protobuf:"bytes,4,opt,name=stopRequest" json:"stopRequest,omitempty"`
	StopResponse               *StopResponse               `protobuf:"bytes,5,opt,name=stopResponse" json:"stopResponse,omitempty"`
	GetStatusRequest           *GetStatusRequest           `protobuf:"bytes,6,opt,name=getStatusRequest" json:"getStatusRequest,omitempty"`
	GetStatusResponse          *GetStatusResponse          `protobuf:"bytes,7,opt,name=getStatusResponse" json:"getStatusResponse,omitempty"`
	DeleteDatasetShardRequest  *DeleteDatasetShardRequest  `protobuf:"bytes,8,opt,name=deleteDatasetShardRequest" json:"deleteDatasetShardRequest,omitempty"`
	DeleteDatasetShardResponse *DeleteDatasetShardResponse `protobuf:"bytes,9,opt,name=deleteDatasetShardResponse" json:"deleteDatasetShardResponse,omitempty"`
	LocalStatusReportRequest   *LocalStatusReportRequest   `protobuf:"bytes,10,opt,name=localStatusReportRequest" json:"localStatusReportRequest,omitempty"`
	LocalStatusReportResponse  *LocalStatusReportResponse  `protobuf:"bytes,11,opt,name=localStatusReportResponse" json:"localStatusReportResponse,omitempty"`
	ReadRequest                *ReadRequest                `protobuf:"bytes,12,opt,name=readRequest" json:"readRequest,omitempty"`
	XXX_unrecognized           []byte                      `json:"-"`
}

func (m *ControlMessage) Reset()                    { *m = ControlMessage{} }
func (m *ControlMessage) String() string            { return proto.CompactTextString(m) }
func (*ControlMessage) ProtoMessage()               {}
func (*ControlMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ControlMessage) GetWriteRequest() *WriteRequest {
	if m != nil {
		return m.WriteRequest
	}
	return nil
}

func (m *ControlMessage) GetStartRequest() *StartRequest {
	if m != nil {
		return m.StartRequest
	}
	return nil
}

func (m *ControlMessage) GetStartResponse() *StartResponse {
	if m != nil {
		return m.StartResponse
	}
	return nil
}

func (m *ControlMessage) GetStopRequest() *StopRequest {
	if m != nil {
		return m.StopRequest
	}
	return nil
}

func (m *ControlMessage) GetStopResponse() *StopResponse {
	if m != nil {
		return m.StopResponse
	}
	return nil
}

func (m *ControlMessage) GetGetStatusRequest() *GetStatusRequest {
	if m != nil {
		return m.GetStatusRequest
	}
	return nil
}

func (m *ControlMessage) GetGetStatusResponse() *GetStatusResponse {
	if m != nil {
		return m.GetStatusResponse
	}
	return nil
}

func (m *ControlMessage) GetDeleteDatasetShardRequest() *DeleteDatasetShardRequest {
	if m != nil {
		return m.DeleteDatasetShardRequest
	}
	return nil
}

func (m *ControlMessage) GetDeleteDatasetShardResponse() *DeleteDatasetShardResponse {
	if m != nil {
		return m.DeleteDatasetShardResponse
	}
	return nil
}

func (m *ControlMessage) GetLocalStatusReportRequest() *LocalStatusReportRequest {
	if m != nil {
		return m.LocalStatusReportRequest
	}
	return nil
}

func (m *ControlMessage) GetLocalStatusReportResponse() *LocalStatusReportResponse {
	if m != nil {
		return m.LocalStatusReportResponse
	}
	return nil
}

func (m *ControlMessage) GetReadRequest() *ReadRequest {
	if m != nil {
		return m.ReadRequest
	}
	return nil
}

type NetChan struct {
	Server           *string `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	Port             *int32  `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NetChan) Reset()                    { *m = NetChan{} }
func (m *NetChan) String() string            { return proto.CompactTextString(m) }
func (*NetChan) ProtoMessage()               {}
func (*NetChan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NetChan) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *NetChan) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type ComputeResource struct {
	CpuCount         *int32 `protobuf:"varint,1,req,name=cpuCount" json:"cpuCount,omitempty"`
	CpuLevel         *int32 `protobuf:"varint,2,req,name=cpuLevel" json:"cpuLevel,omitempty"`
	GpuCount         *int32 `protobuf:"varint,3,req,name=gpuCount" json:"gpuCount,omitempty"`
	GpuLevel         *int32 `protobuf:"varint,4,req,name=gpuLevel" json:"gpuLevel,omitempty"`
	Memory           *int32 `protobuf:"varint,5,req,name=memory" json:"memory,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ComputeResource) Reset()                    { *m = ComputeResource{} }
func (m *ComputeResource) String() string            { return proto.CompactTextString(m) }
func (*ComputeResource) ProtoMessage()               {}
func (*ComputeResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ComputeResource) GetCpuCount() int32 {
	if m != nil && m.CpuCount != nil {
		return *m.CpuCount
	}
	return 0
}

func (m *ComputeResource) GetCpuLevel() int32 {
	if m != nil && m.CpuLevel != nil {
		return *m.CpuLevel
	}
	return 0
}

func (m *ComputeResource) GetGpuCount() int32 {
	if m != nil && m.GpuCount != nil {
		return *m.GpuCount
	}
	return 0
}

func (m *ComputeResource) GetGpuLevel() int32 {
	if m != nil && m.GpuLevel != nil {
		return *m.GpuLevel
	}
	return 0
}

func (m *ComputeResource) GetMemory() int32 {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return 0
}

type StartRequest struct {
	Instructions     *InstructionSet  `protobuf:"bytes,1,req,name=instructions" json:"instructions,omitempty"`
	Files            []string         `protobuf:"bytes,2,rep,name=files" json:"files,omitempty"`
	Dir              *string          `protobuf:"bytes,3,req,name=dir" json:"dir,omitempty"`
	Resource         *ComputeResource `protobuf:"bytes,4,req,name=resource" json:"resource,omitempty"`
	Host             *string          `protobuf:"bytes,5,req,name=host" json:"host,omitempty"`
	Port             *int32           `protobuf:"varint,6,req,name=port" json:"port,omitempty"`
	HashCode         *uint32          `protobuf:"varint,7,req,name=hashCode" json:"hashCode,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StartRequest) GetInstructions() *InstructionSet {
	if m != nil {
		return m.Instructions
	}
	return nil
}

func (m *StartRequest) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *StartRequest) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *StartRequest) GetResource() *ComputeResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *StartRequest) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *StartRequest) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *StartRequest) GetHashCode() uint32 {
	if m != nil && m.HashCode != nil {
		return *m.HashCode
	}
	return 0
}

type InstructionSet struct {
	Instructions     []*Instruction `protobuf:"bytes,1,rep,name=instructions" json:"instructions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *InstructionSet) Reset()                    { *m = InstructionSet{} }
func (m *InstructionSet) String() string            { return proto.CompactTextString(m) }
func (*InstructionSet) ProtoMessage()               {}
func (*InstructionSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InstructionSet) GetInstructions() []*Instruction {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type Instruction struct {
	ScatterPartitions        *ScatterPartitions        `protobuf:"bytes,1,opt,name=scatterPartitions" json:"scatterPartitions,omitempty"`
	CollectPartitions        *CollectPartitions        `protobuf:"bytes,2,opt,name=collectPartitions" json:"collectPartitions,omitempty"`
	LocalSort                *LocalSort                `protobuf:"bytes,3,opt,name=localSort" json:"localSort,omitempty"`
	MergeSortedTo            *MergeSortedTo            `protobuf:"bytes,4,opt,name=mergeSortedTo" json:"mergeSortedTo,omitempty"`
	JoinPartitionedSorted    *JoinPartitionedSorted    `protobuf:"bytes,5,opt,name=joinPartitionedSorted" json:"joinPartitionedSorted,omitempty"`
	CoGroupPartitionedSorted *CoGroupPartitionedSorted `protobuf:"bytes,6,opt,name=coGroupPartitionedSorted" json:"coGroupPartitionedSorted,omitempty"`
	PipeAsArgs               *PipeAsArgs               `protobuf:"bytes,7,opt,name=pipeAsArgs" json:"pipeAsArgs,omitempty"`
	Script                   *Script                   `protobuf:"bytes,8,opt,name=script" json:"script,omitempty"`
	XXX_unrecognized         []byte                    `json:"-"`
}

func (m *Instruction) Reset()                    { *m = Instruction{} }
func (m *Instruction) String() string            { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()               {}
func (*Instruction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Instruction) GetScatterPartitions() *ScatterPartitions {
	if m != nil {
		return m.ScatterPartitions
	}
	return nil
}

func (m *Instruction) GetCollectPartitions() *CollectPartitions {
	if m != nil {
		return m.CollectPartitions
	}
	return nil
}

func (m *Instruction) GetLocalSort() *LocalSort {
	if m != nil {
		return m.LocalSort
	}
	return nil
}

func (m *Instruction) GetMergeSortedTo() *MergeSortedTo {
	if m != nil {
		return m.MergeSortedTo
	}
	return nil
}

func (m *Instruction) GetJoinPartitionedSorted() *JoinPartitionedSorted {
	if m != nil {
		return m.JoinPartitionedSorted
	}
	return nil
}

func (m *Instruction) GetCoGroupPartitionedSorted() *CoGroupPartitionedSorted {
	if m != nil {
		return m.CoGroupPartitionedSorted
	}
	return nil
}

func (m *Instruction) GetPipeAsArgs() *PipeAsArgs {
	if m != nil {
		return m.PipeAsArgs
	}
	return nil
}

func (m *Instruction) GetScript() *Script {
	if m != nil {
		return m.Script
	}
	return nil
}

type ScatterPartitions struct {
	InputShard           *DatasetShard           `protobuf:"bytes,1,req,name=InputShard,json=inputShard" json:"InputShard,omitempty"`
	OutputShardLocations []*DatasetShardLocation `protobuf:"bytes,2,rep,name=OutputShardLocations,json=outputShardLocations" json:"OutputShardLocations,omitempty"`
	ShardCount           *int32                  `protobuf:"varint,3,req,name=shardCount" json:"shardCount,omitempty"`
	XXX_unrecognized     []byte                  `json:"-"`
}

func (m *ScatterPartitions) Reset()                    { *m = ScatterPartitions{} }
func (m *ScatterPartitions) String() string            { return proto.CompactTextString(m) }
func (*ScatterPartitions) ProtoMessage()               {}
func (*ScatterPartitions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ScatterPartitions) GetInputShard() *DatasetShard {
	if m != nil {
		return m.InputShard
	}
	return nil
}

func (m *ScatterPartitions) GetOutputShardLocations() []*DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocations
	}
	return nil
}

func (m *ScatterPartitions) GetShardCount() int32 {
	if m != nil && m.ShardCount != nil {
		return *m.ShardCount
	}
	return 0
}

type CollectPartitions struct {
	InputShardLocations []*DatasetShardLocation `protobuf:"bytes,1,rep,name=inputShardLocations" json:"inputShardLocations,omitempty"`
	OutputShard         *DatasetShard           `protobuf:"bytes,2,req,name=OutputShard,json=outputShard" json:"OutputShard,omitempty"`
	XXX_unrecognized    []byte                  `json:"-"`
}

func (m *CollectPartitions) Reset()                    { *m = CollectPartitions{} }
func (m *CollectPartitions) String() string            { return proto.CompactTextString(m) }
func (*CollectPartitions) ProtoMessage()               {}
func (*CollectPartitions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CollectPartitions) GetInputShardLocations() []*DatasetShardLocation {
	if m != nil {
		return m.InputShardLocations
	}
	return nil
}

func (m *CollectPartitions) GetOutputShard() *DatasetShard {
	if m != nil {
		return m.OutputShard
	}
	return nil
}

type LocalSort struct {
	InputShard       *DatasetShard `protobuf:"bytes,1,req,name=InputShard,json=inputShard" json:"InputShard,omitempty"`
	OutputShard      *DatasetShard `protobuf:"bytes,2,req,name=OutputShard,json=outputShard" json:"OutputShard,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *LocalSort) Reset()                    { *m = LocalSort{} }
func (m *LocalSort) String() string            { return proto.CompactTextString(m) }
func (*LocalSort) ProtoMessage()               {}
func (*LocalSort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *LocalSort) GetInputShard() *DatasetShard {
	if m != nil {
		return m.InputShard
	}
	return nil
}

func (m *LocalSort) GetOutputShard() *DatasetShard {
	if m != nil {
		return m.OutputShard
	}
	return nil
}

type MergeSortedTo struct {
	InputShardLocations []*DatasetShardLocation `protobuf:"bytes,1,rep,name=inputShardLocations" json:"inputShardLocations,omitempty"`
	OutputShard         *DatasetShard           `protobuf:"bytes,2,req,name=OutputShard,json=outputShard" json:"OutputShard,omitempty"`
	XXX_unrecognized    []byte                  `json:"-"`
}

func (m *MergeSortedTo) Reset()                    { *m = MergeSortedTo{} }
func (m *MergeSortedTo) String() string            { return proto.CompactTextString(m) }
func (*MergeSortedTo) ProtoMessage()               {}
func (*MergeSortedTo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MergeSortedTo) GetInputShardLocations() []*DatasetShardLocation {
	if m != nil {
		return m.InputShardLocations
	}
	return nil
}

func (m *MergeSortedTo) GetOutputShard() *DatasetShard {
	if m != nil {
		return m.OutputShard
	}
	return nil
}

type JoinPartitionedSorted struct {
	LeftInputShardLocation  *DatasetShardLocation `protobuf:"bytes,1,req,name=leftInputShardLocation" json:"leftInputShardLocation,omitempty"`
	RightInputShardLocation *DatasetShardLocation `protobuf:"bytes,2,req,name=rightInputShardLocation" json:"rightInputShardLocation,omitempty"`
	OutputShard             *DatasetShard         `protobuf:"bytes,3,req,name=OutputShard,json=outputShard" json:"OutputShard,omitempty"`
	IsLeftOuterJoin         *bool                 `protobuf:"varint,4,req,name=isLeftOuterJoin" json:"isLeftOuterJoin,omitempty"`
	IsRightOuterJoin        *bool                 `protobuf:"varint,5,req,name=isRightOuterJoin" json:"isRightOuterJoin,omitempty"`
	XXX_unrecognized        []byte                `json:"-"`
}

func (m *JoinPartitionedSorted) Reset()                    { *m = JoinPartitionedSorted{} }
func (m *JoinPartitionedSorted) String() string            { return proto.CompactTextString(m) }
func (*JoinPartitionedSorted) ProtoMessage()               {}
func (*JoinPartitionedSorted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *JoinPartitionedSorted) GetLeftInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.LeftInputShardLocation
	}
	return nil
}

func (m *JoinPartitionedSorted) GetRightInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.RightInputShardLocation
	}
	return nil
}

func (m *JoinPartitionedSorted) GetOutputShard() *DatasetShard {
	if m != nil {
		return m.OutputShard
	}
	return nil
}

func (m *JoinPartitionedSorted) GetIsLeftOuterJoin() bool {
	if m != nil && m.IsLeftOuterJoin != nil {
		return *m.IsLeftOuterJoin
	}
	return false
}

func (m *JoinPartitionedSorted) GetIsRightOuterJoin() bool {
	if m != nil && m.IsRightOuterJoin != nil {
		return *m.IsRightOuterJoin
	}
	return false
}

type CoGroupPartitionedSorted struct {
	LeftInputShardLocation  *DatasetShardLocation `protobuf:"bytes,1,req,name=leftInputShardLocation" json:"leftInputShardLocation,omitempty"`
	RightInputShardLocation *DatasetShardLocation `protobuf:"bytes,2,req,name=rightInputShardLocation" json:"rightInputShardLocation,omitempty"`
	OutputShard             *DatasetShard         `protobuf:"bytes,3,req,name=OutputShard,json=outputShard" json:"OutputShard,omitempty"`
	XXX_unrecognized        []byte                `json:"-"`
}

func (m *CoGroupPartitionedSorted) Reset()                    { *m = CoGroupPartitionedSorted{} }
func (m *CoGroupPartitionedSorted) String() string            { return proto.CompactTextString(m) }
func (*CoGroupPartitionedSorted) ProtoMessage()               {}
func (*CoGroupPartitionedSorted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CoGroupPartitionedSorted) GetLeftInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.LeftInputShardLocation
	}
	return nil
}

func (m *CoGroupPartitionedSorted) GetRightInputShardLocation() *DatasetShardLocation {
	if m != nil {
		return m.RightInputShardLocation
	}
	return nil
}

func (m *CoGroupPartitionedSorted) GetOutputShard() *DatasetShard {
	if m != nil {
		return m.OutputShard
	}
	return nil
}

type PipeAsArgs struct {
	InputShard       *DatasetShard `protobuf:"bytes,1,req,name=InputShard,json=inputShard" json:"InputShard,omitempty"`
	OutputShard      *DatasetShard `protobuf:"bytes,2,req,name=OutputShard,json=outputShard" json:"OutputShard,omitempty"`
	Code             *string       `protobuf:"bytes,3,req,name=code" json:"code,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PipeAsArgs) Reset()                    { *m = PipeAsArgs{} }
func (m *PipeAsArgs) String() string            { return proto.CompactTextString(m) }
func (*PipeAsArgs) ProtoMessage()               {}
func (*PipeAsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PipeAsArgs) GetInputShard() *DatasetShard {
	if m != nil {
		return m.InputShard
	}
	return nil
}

func (m *PipeAsArgs) GetOutputShard() *DatasetShard {
	if m != nil {
		return m.OutputShard
	}
	return nil
}

func (m *PipeAsArgs) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

type Script struct {
	InputShard       *DatasetShard `protobuf:"bytes,1,req,name=InputShard,json=inputShard" json:"InputShard,omitempty"`
	OutputShard      *DatasetShard `protobuf:"bytes,2,req,name=OutputShard,json=outputShard" json:"OutputShard,omitempty"`
	Name             *string       `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	IsPipe           *bool         `protobuf:"varint,4,req,name=isPipe" json:"isPipe,omitempty"`
	Path             *string       `protobuf:"bytes,5,req,name=path" json:"path,omitempty"`
	Args             []string      `protobuf:"bytes,6,rep,name=args" json:"args,omitempty"`
	Env              []string      `protobuf:"bytes,7,rep,name=env" json:"env,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Script) Reset()                    { *m = Script{} }
func (m *Script) String() string            { return proto.CompactTextString(m) }
func (*Script) ProtoMessage()               {}
func (*Script) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Script) GetInputShard() *DatasetShard {
	if m != nil {
		return m.InputShard
	}
	return nil
}

func (m *Script) GetOutputShard() *DatasetShard {
	if m != nil {
		return m.OutputShard
	}
	return nil
}

func (m *Script) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Script) GetIsPipe() bool {
	if m != nil && m.IsPipe != nil {
		return *m.IsPipe
	}
	return false
}

func (m *Script) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Script) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Script) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

type DatasetShard struct {
	FlowName         *string `protobuf:"bytes,1,req,name=FlowName,json=flowName" json:"FlowName,omitempty"`
	DatasetId        *int32  `protobuf:"varint,2,req,name=DatasetId,json=datasetId" json:"DatasetId,omitempty"`
	DatasetShardId   *int32  `protobuf:"varint,3,req,name=DatasetShardId,json=datasetShardId" json:"DatasetShardId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DatasetShard) Reset()                    { *m = DatasetShard{} }
func (m *DatasetShard) String() string            { return proto.CompactTextString(m) }
func (*DatasetShard) ProtoMessage()               {}
func (*DatasetShard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DatasetShard) GetFlowName() string {
	if m != nil && m.FlowName != nil {
		return *m.FlowName
	}
	return ""
}

func (m *DatasetShard) GetDatasetId() int32 {
	if m != nil && m.DatasetId != nil {
		return *m.DatasetId
	}
	return 0
}

func (m *DatasetShard) GetDatasetShardId() int32 {
	if m != nil && m.DatasetShardId != nil {
		return *m.DatasetShardId
	}
	return 0
}

type DatasetShardLocation struct {
	Shard            *DatasetShard `protobuf:"bytes,1,req,name=shard" json:"shard,omitempty"`
	Host             *string       `protobuf:"bytes,2,req,name=Host,json=host" json:"Host,omitempty"`
	Port             *int32        `protobuf:"varint,3,req,name=Port,json=port" json:"Port,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *DatasetShardLocation) Reset()                    { *m = DatasetShardLocation{} }
func (m *DatasetShardLocation) String() string            { return proto.CompactTextString(m) }
func (*DatasetShardLocation) ProtoMessage()               {}
func (*DatasetShardLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DatasetShardLocation) GetShard() *DatasetShard {
	if m != nil {
		return m.Shard
	}
	return nil
}

func (m *DatasetShardLocation) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *DatasetShardLocation) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type StartResponse struct {
	Pid              *int32     `protobuf:"varint,1,req,name=pid" json:"pid,omitempty"`
	Error            *string    `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Stderr           *NetChan   `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
	Outputs          []*NetChan `protobuf:"bytes,4,rep,name=outputs" json:"outputs,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *StartResponse) Reset()                    { *m = StartResponse{} }
func (m *StartResponse) String() string            { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()               {}
func (*StartResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *StartResponse) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *StartResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *StartResponse) GetStderr() *NetChan {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *StartResponse) GetOutputs() []*NetChan {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type StopRequest struct {
	StartRequestHash *uint32 `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *StopRequest) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

type StopResponse struct {
	StartRequestHash *uint32 `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StopResponse) Reset()                    { *m = StopResponse{} }
func (m *StopResponse) String() string            { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()               {}
func (*StopResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *StopResponse) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

func (m *StopResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type GetStatusRequest struct {
	StartRequestHash *uint32 `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetStatusRequest) Reset()                    { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()               {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetStatusRequest) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

type ChannelStatus struct {
	Length           *int64  `protobuf:"varint,1,req,name=length" json:"length,omitempty"`
	StartTime        *int64  `protobuf:"varint,2,opt,name=startTime" json:"startTime,omitempty"`
	StopTime         *int64  `protobuf:"varint,3,opt,name=stopTime" json:"stopTime,omitempty"`
	Name             *string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChannelStatus) Reset()                    { *m = ChannelStatus{} }
func (m *ChannelStatus) String() string            { return proto.CompactTextString(m) }
func (*ChannelStatus) ProtoMessage()               {}
func (*ChannelStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ChannelStatus) GetLength() int64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *ChannelStatus) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *ChannelStatus) GetStopTime() int64 {
	if m != nil && m.StopTime != nil {
		return *m.StopTime
	}
	return 0
}

func (m *ChannelStatus) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type GetStatusResponse struct {
	StartRequestHash *uint32          `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            *string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	InputStatuses    []*ChannelStatus `protobuf:"bytes,3,rep,name=inputStatuses" json:"inputStatuses,omitempty"`
	OutputStatuses   []*ChannelStatus `protobuf:"bytes,4,rep,name=outputStatuses" json:"outputStatuses,omitempty"`
	RequestTime      *int64           `protobuf:"varint,5,opt,name=requestTime" json:"requestTime,omitempty"`
	StartTime        *int64           `protobuf:"varint,6,opt,name=startTime" json:"startTime,omitempty"`
	StopTime         *int64           `protobuf:"varint,7,opt,name=stopTime" json:"stopTime,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetStatusResponse) Reset()                    { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()               {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetStatusResponse) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

func (m *GetStatusResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *GetStatusResponse) GetInputStatuses() []*ChannelStatus {
	if m != nil {
		return m.InputStatuses
	}
	return nil
}

func (m *GetStatusResponse) GetOutputStatuses() []*ChannelStatus {
	if m != nil {
		return m.OutputStatuses
	}
	return nil
}

func (m *GetStatusResponse) GetRequestTime() int64 {
	if m != nil && m.RequestTime != nil {
		return *m.RequestTime
	}
	return 0
}

func (m *GetStatusResponse) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *GetStatusResponse) GetStopTime() int64 {
	if m != nil && m.StopTime != nil {
		return *m.StopTime
	}
	return 0
}

type DeleteDatasetShardRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteDatasetShardRequest) Reset()                    { *m = DeleteDatasetShardRequest{} }
func (m *DeleteDatasetShardRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDatasetShardRequest) ProtoMessage()               {}
func (*DeleteDatasetShardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *DeleteDatasetShardRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type DeleteDatasetShardResponse struct {
	Error            *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteDatasetShardResponse) Reset()                    { *m = DeleteDatasetShardResponse{} }
func (m *DeleteDatasetShardResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDatasetShardResponse) ProtoMessage()               {}
func (*DeleteDatasetShardResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *DeleteDatasetShardResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type LocalStatusReportRequest struct {
	StartRequestHash *uint32          `protobuf:"varint,1,req,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            *string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	InputStatuses    []*ChannelStatus `protobuf:"bytes,3,rep,name=inputStatuses" json:"inputStatuses,omitempty"`
	OutputStatuses   []*ChannelStatus `protobuf:"bytes,4,rep,name=outputStatuses" json:"outputStatuses,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *LocalStatusReportRequest) Reset()                    { *m = LocalStatusReportRequest{} }
func (m *LocalStatusReportRequest) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusReportRequest) ProtoMessage()               {}
func (*LocalStatusReportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *LocalStatusReportRequest) GetStartRequestHash() uint32 {
	if m != nil && m.StartRequestHash != nil {
		return *m.StartRequestHash
	}
	return 0
}

func (m *LocalStatusReportRequest) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *LocalStatusReportRequest) GetInputStatuses() []*ChannelStatus {
	if m != nil {
		return m.InputStatuses
	}
	return nil
}

func (m *LocalStatusReportRequest) GetOutputStatuses() []*ChannelStatus {
	if m != nil {
		return m.OutputStatuses
	}
	return nil
}

type LocalStatusReportResponse struct {
	Error            *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LocalStatusReportResponse) Reset()                    { *m = LocalStatusReportResponse{} }
func (m *LocalStatusReportResponse) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusReportResponse) ProtoMessage()               {}
func (*LocalStatusReportResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *LocalStatusReportResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type WriteRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *WriteRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type ReadRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ReadRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ControlMessage)(nil), "cmd.ControlMessage")
	proto.RegisterType((*NetChan)(nil), "cmd.NetChan")
	proto.RegisterType((*ComputeResource)(nil), "cmd.ComputeResource")
	proto.RegisterType((*StartRequest)(nil), "cmd.StartRequest")
	proto.RegisterType((*InstructionSet)(nil), "cmd.InstructionSet")
	proto.RegisterType((*Instruction)(nil), "cmd.Instruction")
	proto.RegisterType((*ScatterPartitions)(nil), "cmd.ScatterPartitions")
	proto.RegisterType((*CollectPartitions)(nil), "cmd.CollectPartitions")
	proto.RegisterType((*LocalSort)(nil), "cmd.LocalSort")
	proto.RegisterType((*MergeSortedTo)(nil), "cmd.MergeSortedTo")
	proto.RegisterType((*JoinPartitionedSorted)(nil), "cmd.JoinPartitionedSorted")
	proto.RegisterType((*CoGroupPartitionedSorted)(nil), "cmd.CoGroupPartitionedSorted")
	proto.RegisterType((*PipeAsArgs)(nil), "cmd.PipeAsArgs")
	proto.RegisterType((*Script)(nil), "cmd.Script")
	proto.RegisterType((*DatasetShard)(nil), "cmd.DatasetShard")
	proto.RegisterType((*DatasetShardLocation)(nil), "cmd.DatasetShardLocation")
	proto.RegisterType((*StartResponse)(nil), "cmd.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "cmd.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "cmd.StopResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "cmd.GetStatusRequest")
	proto.RegisterType((*ChannelStatus)(nil), "cmd.ChannelStatus")
	proto.RegisterType((*GetStatusResponse)(nil), "cmd.GetStatusResponse")
	proto.RegisterType((*DeleteDatasetShardRequest)(nil), "cmd.DeleteDatasetShardRequest")
	proto.RegisterType((*DeleteDatasetShardResponse)(nil), "cmd.DeleteDatasetShardResponse")
	proto.RegisterType((*LocalStatusReportRequest)(nil), "cmd.LocalStatusReportRequest")
	proto.RegisterType((*LocalStatusReportResponse)(nil), "cmd.LocalStatusReportResponse")
	proto.RegisterType((*WriteRequest)(nil), "cmd.WriteRequest")
	proto.RegisterType((*ReadRequest)(nil), "cmd.ReadRequest")
}

func init() { proto.RegisterFile("control_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xdc, 0x58, 0xcd, 0x6e, 0x1c, 0xc5,
	0x13, 0xd7, 0xec, 0x97, 0xbd, 0xb5, 0x6b, 0xc7, 0xee, 0xd8, 0xfe, 0xaf, 0xad, 0x3f, 0xc1, 0x0c,
	0x28, 0x58, 0x08, 0x25, 0xc4, 0x10, 0xf1, 0x71, 0x40, 0x8a, 0x36, 0x4a, 0x62, 0x70, 0x12, 0xd3,
	0x8e, 0x84, 0x90, 0x90, 0xa2, 0xd1, 0x4c, 0x7b, 0x77, 0xd0, 0xee, 0xf6, 0xd0, 0xdd, 0xe3, 0x88,
	0x3b, 0x48, 0x5c, 0x39, 0x70, 0xe0, 0x09, 0x78, 0x02, 0x5e, 0x82, 0x23, 0x07, 0xc4, 0x0b, 0xf0,
	0x0c, 0x5c, 0x51, 0x75, 0xf7, 0xcc, 0xf4, 0xec, 0xcc, 0x38, 0x24, 0x48, 0x11, 0x70, 0xeb, 0xfa,
	0xf8, 0x55, 0x57, 0xff, 0xa6, 0xba, 0xb6, 0x7a, 0x61, 0x3b, 0xe4, 0x0b, 0x25, 0xf8, 0xec, 0xf1,
	0x9c, 0x49, 0x19, 0x4c, 0xd8, 0xb5, 0x44, 0x70, 0xc5, 0x49, 0x3b, 0x9c, 0x47, 0xfe, 0x6f, 0x3d,
	0x58, 0x1f, 0x1b, 0xf3, 0x7d, 0x63, 0x25, 0x37, 0x61, 0xf8, 0x44, 0xc4, 0x8a, 0x51, 0xf6, 0x65,
	0xca, 0xa4, 0x1a, 0x79, 0xfb, 0xde, 0xc1, 0xe0, 0x70, 0xf3, 0x5a, 0x38, 0x8f, 0xae, 0x7d, 0xea,
	0x18, 0x68, 0xc9, 0x0d, 0x61, 0x52, 0x05, 0x42, 0x65, 0xb0, 0x96, 0x03, 0x3b, 0x75, 0x0c, 0xb4,
	0xe4, 0x46, 0xde, 0x83, 0x35, 0x2b, 0xcb, 0x84, 0x2f, 0x24, 0x1b, 0xb5, 0x35, 0x8e, 0xb8, 0x38,
	0x63, 0xa1, 0x65, 0x47, 0x72, 0x08, 0x03, 0xa9, 0x78, 0x92, 0xed, 0xd7, 0xd1, 0xb8, 0x0d, 0x8b,
	0xcb, 0xf5, 0xd4, 0x75, 0x32, 0x49, 0xa2, 0x68, 0x37, 0xeb, 0x96, 0x92, 0x2c, 0x0c, 0xb4, 0xe4,
	0x46, 0x6e, 0xc1, 0xc6, 0x84, 0xa9, 0x53, 0x15, 0xa8, 0x54, 0x66, 0xfb, 0xf5, 0x34, 0x74, 0x5b,
	0x43, 0xef, 0x2e, 0x19, 0x69, 0xc5, 0x9d, 0xdc, 0x86, 0x4d, 0x47, 0x67, 0xb7, 0x5f, 0xd1, 0x31,
	0x76, 0x96, 0x63, 0xd8, 0x1c, 0xaa, 0x00, 0xf2, 0x39, 0xec, 0x46, 0x6c, 0xc6, 0x14, 0xbb, 0x1d,
	0xa8, 0x40, 0x32, 0x75, 0x3a, 0x0d, 0x44, 0x94, 0x65, 0xb4, 0xaa, 0xa3, 0x5d, 0xd1, 0xd1, 0x6e,
	0x37, 0x79, 0xd1, 0xe6, 0x00, 0xe4, 0x31, 0xec, 0xd5, 0x19, 0x6d, 0xb2, 0x7d, 0x1d, 0xfe, 0xe5,
	0xc6, 0xf0, 0x36, 0xeb, 0x0b, 0x42, 0x90, 0xcf, 0x60, 0x34, 0xe3, 0x61, 0x30, 0xcb, 0x4e, 0x95,
	0xf0, 0xa2, 0x5e, 0x40, 0x87, 0x7f, 0x49, 0x87, 0x3f, 0x6e, 0x70, 0xa2, 0x8d, 0x70, 0x64, 0xa6,
	0xc6, 0x66, 0x53, 0x1f, 0x38, 0xcc, 0x1c, 0x37, 0x79, 0xd1, 0xe6, 0x00, 0x58, 0x6b, 0x82, 0x05,
	0x39, 0xd3, 0x43, 0xa7, 0xd6, 0x68, 0xa1, 0xa7, 0xae, 0x93, 0x7f, 0x13, 0x56, 0x1e, 0x30, 0x35,
	0x9e, 0x06, 0x0b, 0xb2, 0x03, 0x3d, 0xc9, 0xc4, 0x39, 0x13, 0x23, 0x6f, 0xbf, 0x75, 0xd0, 0xa7,
	0x56, 0x22, 0x04, 0x3a, 0xb8, 0xcd, 0xa8, 0xb5, 0xdf, 0x3a, 0xe8, 0x52, 0xbd, 0xf6, 0x7f, 0xf0,
	0xe0, 0xd2, 0x98, 0xcf, 0x93, 0x14, 0xaf, 0x96, 0xe4, 0xa9, 0x08, 0x19, 0xd9, 0x83, 0xd5, 0x30,
	0x49, 0xc7, 0x3c, 0x5d, 0x28, 0x1d, 0xa1, 0x4b, 0x73, 0xd9, 0xda, 0x8e, 0xd9, 0x39, 0x9b, 0xd9,
	0x38, 0xb9, 0x8c, 0xb6, 0x49, 0x86, 0x6b, 0x1b, 0xdb, 0xc4, 0xc1, 0x4d, 0x32, 0x5c, 0x27, 0xb7,
	0x19, 0xdc, 0x0e, 0xf4, 0xe6, 0x6c, 0xce, 0xc5, 0x57, 0xa3, 0xae, 0xb6, 0x58, 0xc9, 0xff, 0xdd,
	0x83, 0xa1, 0x7b, 0x97, 0xc9, 0xbb, 0x30, 0x8c, 0x17, 0x52, 0x89, 0x34, 0x54, 0x31, 0x5f, 0x48,
	0x9d, 0xdc, 0xe0, 0xf0, 0xb2, 0x26, 0xe6, 0xa8, 0x30, 0x9c, 0x32, 0x45, 0x4b, 0x8e, 0x64, 0x0b,
	0xba, 0x67, 0xf1, 0x8c, 0xc9, 0x51, 0x6b, 0xbf, 0x7d, 0xd0, 0xa7, 0x46, 0x20, 0x1b, 0xd0, 0x8e,
	0x62, 0xa1, 0x53, 0xed, 0x53, 0x5c, 0x92, 0xb7, 0x60, 0x55, 0x58, 0x16, 0x74, 0x96, 0x83, 0xc3,
	0x2d, 0x1d, 0x7c, 0x89, 0x21, 0x9a, 0x7b, 0x21, 0xa7, 0x53, 0x2e, 0x95, 0xce, 0xbc, 0x4f, 0xf5,
	0x3a, 0xe7, 0xb9, 0x57, 0xf0, 0x8c, 0xe7, 0x9f, 0x06, 0x72, 0x3a, 0xe6, 0x11, 0xde, 0xc3, 0xd6,
	0xc1, 0x1a, 0xcd, 0x65, 0xff, 0x0e, 0xac, 0x97, 0xb3, 0x27, 0xef, 0x54, 0x0e, 0xda, 0xce, 0x2b,
	0xc0, 0x71, 0x2d, 0x9f, 0xd2, 0xff, 0xba, 0x03, 0x03, 0xc7, 0x8a, 0x4d, 0x40, 0x86, 0x81, 0x52,
	0x4c, 0x9c, 0x04, 0x42, 0xc5, 0x59, 0xa8, 0xa2, 0x09, 0x9c, 0x2e, 0x5b, 0x69, 0x15, 0x80, 0x51,
	0x42, 0x3e, 0x9b, 0xb1, 0x50, 0x39, 0x51, 0x5a, 0x4e, 0x94, 0xf1, 0xb2, 0x95, 0x56, 0x01, 0xe4,
	0x4d, 0xe8, 0x9b, 0x7a, 0x47, 0x62, 0x4c, 0xd3, 0x5d, 0x77, 0x2e, 0x08, 0x56, 0x7f, 0xe1, 0x80,
	0x6d, 0x7a, 0xce, 0xc4, 0x84, 0xa1, 0xc0, 0xa2, 0x47, 0xdc, 0xb6, 0x5b, 0xd3, 0xa6, 0xef, 0xbb,
	0x16, 0x5a, 0x76, 0x24, 0x27, 0xb0, 0xfd, 0x05, 0x8f, 0x17, 0xf9, 0xce, 0x2c, 0x32, 0x26, 0xdb,
	0x7b, 0xf7, 0x74, 0x84, 0x8f, 0xea, 0x3c, 0x68, 0x3d, 0x10, 0xbb, 0x48, 0xc8, 0xef, 0x0a, 0x9e,
	0x26, 0xd5, 0xa0, 0x3d, 0xa7, 0x8b, 0x8c, 0x1b, 0x9c, 0x68, 0x23, 0x9c, 0x5c, 0x07, 0x48, 0xe2,
	0x84, 0xdd, 0x92, 0xb7, 0xc4, 0x44, 0xda, 0xf6, 0x7c, 0x49, 0x07, 0x3b, 0xc9, 0xd5, 0xd4, 0x71,
	0x21, 0xaf, 0x42, 0x4f, 0x86, 0x22, 0x4e, 0xb2, 0xee, 0x3b, 0xb0, 0x9f, 0x11, 0x55, 0xd4, 0x9a,
	0xfc, 0x9f, 0x3c, 0xd8, 0xac, 0x7c, 0x59, 0x72, 0x03, 0xe0, 0x68, 0x91, 0xa4, 0xa6, 0x45, 0xda,
	0x9b, 0x63, 0x7e, 0x89, 0x4a, 0xbd, 0x13, 0xe2, 0xdc, 0x89, 0xdc, 0x87, 0xad, 0x87, 0xa9, 0xca,
	0x44, 0xfc, 0x50, 0xd9, 0xc7, 0xc7, 0x6a, 0xdc, 0xad, 0x80, 0x33, 0x0f, 0xba, 0xc5, 0x6b, 0x60,
	0xe4, 0x0a, 0x80, 0x44, 0x8d, 0xdb, 0x20, 0x1c, 0x8d, 0xff, 0xbd, 0x07, 0x9b, 0x95, 0x5a, 0x22,
	0x1f, 0xc3, 0xe5, 0x22, 0xa5, 0x22, 0x07, 0xef, 0x69, 0x39, 0xd4, 0xa1, 0xc8, 0xdb, 0x30, 0x70,
	0x4e, 0xa4, 0x1b, 0x58, 0x2d, 0x0b, 0x03, 0xe7, 0x00, 0xbe, 0x84, 0x7e, 0x5e, 0xa4, 0xcf, 0x43,
	0xe3, 0x73, 0x6d, 0xfa, 0x9d, 0x07, 0x6b, 0xa5, 0x42, 0xff, 0x07, 0x10, 0xf1, 0x73, 0x0b, 0xb6,
	0x6b, 0xaf, 0x0e, 0xf9, 0x04, 0x76, 0x66, 0xec, 0x4c, 0x1d, 0x55, 0x76, 0xb2, 0x0c, 0x5d, 0x90,
	0x5e, 0x03, 0x90, 0x9c, 0xc2, 0xff, 0x44, 0x3c, 0x99, 0xd6, 0xc5, 0x6c, 0x3d, 0x2d, 0x66, 0x13,
	0x72, 0xf9, 0xd8, 0xed, 0xbf, 0x72, 0x6c, 0x72, 0x00, 0x97, 0x62, 0x79, 0xcc, 0xce, 0xd4, 0xc3,
	0x54, 0x31, 0x81, 0x04, 0xe8, 0xdf, 0x86, 0x55, 0xba, 0xac, 0x26, 0x6f, 0xc0, 0x46, 0x2c, 0x29,
	0xee, 0x5d, 0xb8, 0x76, 0xb5, 0x6b, 0x45, 0xef, 0xff, 0xe1, 0xc1, 0xa8, 0xa9, 0x65, 0xfc, 0xa7,
	0xf9, 0xf4, 0xbf, 0xf5, 0x00, 0x8a, 0xfe, 0xf6, 0xa2, 0x6e, 0x14, 0xfe, 0x2a, 0x87, 0xf8, 0xeb,
	0x6b, 0x7e, 0xee, 0xf5, 0xda, 0xff, 0xd5, 0x83, 0x9e, 0xe9, 0x9e, 0x2f, 0x32, 0x8d, 0x45, 0x30,
	0xcf, 0xd3, 0xc0, 0x35, 0x0e, 0x40, 0xb1, 0x44, 0x4a, 0x6c, 0x61, 0x59, 0x49, 0x0f, 0x12, 0x81,
	0x9a, 0x66, 0xc3, 0x05, 0xae, 0x51, 0x17, 0xe0, 0xaf, 0x45, 0x4f, 0x4f, 0x32, 0x7a, 0x8d, 0x83,
	0x0c, 0x5b, 0x9c, 0x8f, 0x56, 0xb4, 0x0a, 0x97, 0x7e, 0x02, 0x43, 0x37, 0x05, 0x1c, 0x3f, 0xee,
	0xcc, 0xf8, 0x93, 0x07, 0xb8, 0xb3, 0x19, 0x0a, 0x57, 0xcf, 0xac, 0x4c, 0xfe, 0x0f, 0x7d, 0xeb,
	0x7b, 0x14, 0xd9, 0x99, 0xae, 0x1f, 0x65, 0x0a, 0x72, 0x15, 0xd6, 0xdd, 0x48, 0x47, 0x91, 0xed,
	0xdc, 0xeb, 0x51, 0x49, 0xeb, 0x4f, 0x60, 0xab, 0xae, 0x76, 0xc8, 0xeb, 0xd0, 0x95, 0x17, 0x53,
	0x6a, 0xec, 0x78, 0xb0, 0x7b, 0x5c, 0x9a, 0xe9, 0xd4, 0x99, 0xa4, 0x4e, 0xcc, 0xc0, 0x50, 0x4c,
	0xac, 0xdf, 0x78, 0xb0, 0x56, 0x7a, 0xa9, 0xe1, 0xf1, 0x93, 0x38, 0xb2, 0xa3, 0x2a, 0x2e, 0x71,
	0xde, 0x63, 0x42, 0x70, 0xa1, 0xe7, 0x94, 0x3e, 0x35, 0x02, 0x79, 0x0d, 0x7a, 0x52, 0x45, 0x4c,
	0x08, 0x3b, 0x80, 0x0c, 0x75, 0x2e, 0x76, 0x6a, 0xa6, 0xd6, 0x46, 0xae, 0xc2, 0x8a, 0xf9, 0x5e,
	0x72, 0xd4, 0xd1, 0xbd, 0xb5, 0xec, 0x96, 0x19, 0xfd, 0xf7, 0x61, 0xe0, 0x3c, 0xfc, 0xf0, 0xee,
	0xbb, 0x2f, 0xcd, 0x7b, 0x81, 0x9c, 0xea, 0x8c, 0xd6, 0x68, 0x45, 0xef, 0x9f, 0xe0, 0x5c, 0xeb,
	0x3c, 0xf8, 0x9e, 0x01, 0x5b, 0x7f, 0x34, 0xff, 0x43, 0xd8, 0x58, 0x7e, 0x15, 0x3e, 0x53, 0x46,
	0x29, 0xac, 0xe1, 0xe9, 0x16, 0xcc, 0x3e, 0x48, 0xb0, 0x24, 0x67, 0x6c, 0x31, 0x51, 0x06, 0xd2,
	0xa6, 0x56, 0xc2, 0x62, 0xd1, 0xe0, 0x47, 0xf1, 0x9c, 0xe9, 0x14, 0xda, 0xb4, 0x50, 0x60, 0x99,
	0xe1, 0x4b, 0x56, 0x1b, 0xdb, 0xda, 0x98, 0xcb, 0x79, 0xe1, 0x77, 0x74, 0xde, 0x7a, 0xed, 0xff,
	0xd8, 0x82, 0xcd, 0xca, 0x4b, 0xf4, 0xef, 0xd3, 0x81, 0xf3, 0xa3, 0xb9, 0xa7, 0x3a, 0x30, 0x93,
	0xa3, 0xb6, 0xfe, 0x92, 0x66, 0x7e, 0x2c, 0x1d, 0x94, 0x96, 0x1d, 0xc9, 0x07, 0xb0, 0x6e, 0x6f,
	0x6b, 0x06, 0xed, 0x34, 0x42, 0x97, 0x3c, 0xc9, 0x3e, 0x3e, 0xdb, 0x74, 0x6a, 0x9a, 0x80, 0xae,
	0x26, 0xc0, 0x55, 0x95, 0xd9, 0xeb, 0x5d, 0xc4, 0xde, 0x4a, 0x99, 0x3d, 0xff, 0x3a, 0xec, 0x36,
	0x3e, 0xb2, 0x73, 0x6a, 0xbd, 0xa2, 0xa7, 0xf8, 0x87, 0xb0, 0xd7, 0xfc, 0x6c, 0x2e, 0x68, 0xf3,
	0xdc, 0x2a, 0xfa, 0xc5, 0x83, 0x51, 0xd3, 0x63, 0xf8, 0xdf, 0xfa, 0x55, 0xfc, 0x1b, 0xb0, 0xdb,
	0xf8, 0x08, 0x6f, 0xe0, 0xc1, 0x87, 0xa1, 0xfb, 0xd7, 0x53, 0x2d, 0xbf, 0xaf, 0xc0, 0xc0, 0x79,
	0x8b, 0xd7, 0xb9, 0xfc, 0x19, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x03, 0xab, 0x08, 0x0a, 0x13, 0x00,
	0x00,
}
