// Code generated by protoc-gen-go.
// source: master_agent.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	master_agent.proto

It has these top-level messages:
	ComputeRequest
	ComputeResource
	DataResource
	Location
	Allocation
	AllocationResult
	Heartbeat
	Empty
	DataLocation
	ExecutionRequest
	ExecutionResponse
	ControlMessage
	StopResponse
	GetStatusRequest
	ChannelStatus
	GetStatusResponse
	DeleteDatasetShardRequest
	DeleteDatasetShardResponse
	LocalStatusReportRequest
	LocalStatusReportResponse
	WriteRequest
	ReadRequest
	StopRequest
	InstructionSet
	Instruction
	ScatterPartitions
	RoundRobin
	CollectPartitions
	LocalSort
	LocalTop
	MergeSortedTo
	OrderBy
	JoinPartitionedSorted
	CoGroupPartitionedSorted
	PipeAsArgs
	Script
	InputSplitReader
	AdapterSplitReader
	Broadcast
	LocalHashAndJoinWith
	DatasetShard
	DatasetShardLocation
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ////////////////////////////////////////////////
type ComputeRequest struct {
	DataCenter       string             `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	ComputeResources []*ComputeResource `protobuf:"bytes,2,rep,name=compute_resources,json=computeResources" json:"compute_resources,omitempty"`
}

func (m *ComputeRequest) Reset()                    { *m = ComputeRequest{} }
func (m *ComputeRequest) String() string            { return proto.CompactTextString(m) }
func (*ComputeRequest) ProtoMessage()               {}
func (*ComputeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ComputeRequest) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *ComputeRequest) GetComputeResources() []*ComputeResource {
	if m != nil {
		return m.ComputeResources
	}
	return nil
}

type ComputeResource struct {
	CpuCount int32 `protobuf:"varint,1,opt,name=cpu_count,json=cpuCount" json:"cpu_count,omitempty"`
	CpuLevel int32 `protobuf:"varint,2,opt,name=cpu_level,json=cpuLevel" json:"cpu_level,omitempty"`
	GpuCount int32 `protobuf:"varint,3,opt,name=gpu_count,json=gpuCount" json:"gpu_count,omitempty"`
	GpuLevel int32 `protobuf:"varint,4,opt,name=gpu_level,json=gpuLevel" json:"gpu_level,omitempty"`
	MemoryMb int64 `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb" json:"memory_mb,omitempty"`
	DiskMb   int64 `protobuf:"varint,6,opt,name=disk_mb,json=diskMb" json:"disk_mb,omitempty"`
}

func (m *ComputeResource) Reset()                    { *m = ComputeResource{} }
func (m *ComputeResource) String() string            { return proto.CompactTextString(m) }
func (*ComputeResource) ProtoMessage()               {}
func (*ComputeResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ComputeResource) GetCpuCount() int32 {
	if m != nil {
		return m.CpuCount
	}
	return 0
}

func (m *ComputeResource) GetCpuLevel() int32 {
	if m != nil {
		return m.CpuLevel
	}
	return 0
}

func (m *ComputeResource) GetGpuCount() int32 {
	if m != nil {
		return m.GpuCount
	}
	return 0
}

func (m *ComputeResource) GetGpuLevel() int32 {
	if m != nil {
		return m.GpuLevel
	}
	return 0
}

func (m *ComputeResource) GetMemoryMb() int64 {
	if m != nil {
		return m.MemoryMb
	}
	return 0
}

func (m *ComputeResource) GetDiskMb() int64 {
	if m != nil {
		return m.DiskMb
	}
	return 0
}

type DataResource struct {
	Location *Location `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Size     int64     `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *DataResource) Reset()                    { *m = DataResource{} }
func (m *DataResource) String() string            { return proto.CompactTextString(m) }
func (*DataResource) ProtoMessage()               {}
func (*DataResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DataResource) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *DataResource) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Location struct {
	DataCenter string `protobuf:"bytes,1,opt,name=data_center,json=dataCenter" json:"data_center,omitempty"`
	Rack       string `protobuf:"bytes,2,opt,name=rack" json:"rack,omitempty"`
	Server     string `protobuf:"bytes,3,opt,name=server" json:"server,omitempty"`
	Port       int32  `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Location) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *Location) GetRack() string {
	if m != nil {
		return m.Rack
	}
	return ""
}

func (m *Location) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *Location) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Allocation struct {
	Location  *Location        `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Allocated *ComputeResource `protobuf:"bytes,2,opt,name=allocated" json:"allocated,omitempty"`
}

func (m *Allocation) Reset()                    { *m = Allocation{} }
func (m *Allocation) String() string            { return proto.CompactTextString(m) }
func (*Allocation) ProtoMessage()               {}
func (*Allocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Allocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Allocation) GetAllocated() *ComputeResource {
	if m != nil {
		return m.Allocated
	}
	return nil
}

type AllocationResult struct {
	Allocations []*Allocation `protobuf:"bytes,1,rep,name=allocations" json:"allocations,omitempty"`
}

func (m *AllocationResult) Reset()                    { *m = AllocationResult{} }
func (m *AllocationResult) String() string            { return proto.CompactTextString(m) }
func (*AllocationResult) ProtoMessage()               {}
func (*AllocationResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AllocationResult) GetAllocations() []*Allocation {
	if m != nil {
		return m.Allocations
	}
	return nil
}

// ////////////////////////////////////////////////
type Heartbeat struct {
	Location  *Location        `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Resource  *ComputeResource `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	Allocated *ComputeResource `protobuf:"bytes,3,opt,name=allocated" json:"allocated,omitempty"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Heartbeat) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Heartbeat) GetResource() *ComputeResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *Heartbeat) GetAllocated() *ComputeResource {
	if m != nil {
		return m.Allocated
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// ////////////////////////////////////////////////
type DataLocation struct {
	Name     string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Location *Location `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	OnDisk   bool      `protobuf:"varint,3,opt,name=onDisk" json:"onDisk,omitempty"`
}

func (m *DataLocation) Reset()                    { *m = DataLocation{} }
func (m *DataLocation) String() string            { return proto.CompactTextString(m) }
func (*DataLocation) ProtoMessage()               {}
func (*DataLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DataLocation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *DataLocation) GetOnDisk() bool {
	if m != nil {
		return m.OnDisk
	}
	return false
}

type ExecutionRequest struct {
	Instructions *InstructionSet  `protobuf:"bytes,1,opt,name=instructions" json:"instructions,omitempty"`
	Files        []string         `protobuf:"bytes,2,rep,name=files" json:"files,omitempty"`
	Dir          string           `protobuf:"bytes,3,opt,name=dir" json:"dir,omitempty"`
	Resource     *ComputeResource `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	Name         string           `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Host         string           `protobuf:"bytes,6,opt,name=host" json:"host,omitempty"`
	Port         int32            `protobuf:"varint,7,opt,name=port" json:"port,omitempty"`
}

func (m *ExecutionRequest) Reset()                    { *m = ExecutionRequest{} }
func (m *ExecutionRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecutionRequest) ProtoMessage()               {}
func (*ExecutionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ExecutionRequest) GetInstructions() *InstructionSet {
	if m != nil {
		return m.Instructions
	}
	return nil
}

func (m *ExecutionRequest) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *ExecutionRequest) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *ExecutionRequest) GetResource() *ComputeResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ExecutionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExecutionRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ExecutionRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ExecutionResponse struct {
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error  []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *ExecutionResponse) Reset()                    { *m = ExecutionResponse{} }
func (m *ExecutionResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecutionResponse) ProtoMessage()               {}
func (*ExecutionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ExecutionResponse) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *ExecutionResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type ControlMessage struct {
	IsOnDiskIO                bool                       `protobuf:"varint,1,opt,name=isOnDiskIO" json:"isOnDiskIO,omitempty"`
	ReadRequest               *ReadRequest               `protobuf:"bytes,2,opt,name=readRequest" json:"readRequest,omitempty"`
	WriteRequest              *WriteRequest              `protobuf:"bytes,3,opt,name=writeRequest" json:"writeRequest,omitempty"`
	StopRequest               *StopRequest               `protobuf:"bytes,4,opt,name=stopRequest" json:"stopRequest,omitempty"`
	StopResponse              *StopResponse              `protobuf:"bytes,5,opt,name=stopResponse" json:"stopResponse,omitempty"`
	GetStatusRequest          *GetStatusRequest          `protobuf:"bytes,6,opt,name=getStatusRequest" json:"getStatusRequest,omitempty"`
	GetStatusResponse         *GetStatusResponse         `protobuf:"bytes,7,opt,name=getStatusResponse" json:"getStatusResponse,omitempty"`
	LocalStatusReportRequest  *LocalStatusReportRequest  `protobuf:"bytes,8,opt,name=localStatusReportRequest" json:"localStatusReportRequest,omitempty"`
	LocalStatusReportResponse *LocalStatusReportResponse `protobuf:"bytes,9,opt,name=localStatusReportResponse" json:"localStatusReportResponse,omitempty"`
}

func (m *ControlMessage) Reset()                    { *m = ControlMessage{} }
func (m *ControlMessage) String() string            { return proto.CompactTextString(m) }
func (*ControlMessage) ProtoMessage()               {}
func (*ControlMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ControlMessage) GetIsOnDiskIO() bool {
	if m != nil {
		return m.IsOnDiskIO
	}
	return false
}

func (m *ControlMessage) GetReadRequest() *ReadRequest {
	if m != nil {
		return m.ReadRequest
	}
	return nil
}

func (m *ControlMessage) GetWriteRequest() *WriteRequest {
	if m != nil {
		return m.WriteRequest
	}
	return nil
}

func (m *ControlMessage) GetStopRequest() *StopRequest {
	if m != nil {
		return m.StopRequest
	}
	return nil
}

func (m *ControlMessage) GetStopResponse() *StopResponse {
	if m != nil {
		return m.StopResponse
	}
	return nil
}

func (m *ControlMessage) GetGetStatusRequest() *GetStatusRequest {
	if m != nil {
		return m.GetStatusRequest
	}
	return nil
}

func (m *ControlMessage) GetGetStatusResponse() *GetStatusResponse {
	if m != nil {
		return m.GetStatusResponse
	}
	return nil
}

func (m *ControlMessage) GetLocalStatusReportRequest() *LocalStatusReportRequest {
	if m != nil {
		return m.LocalStatusReportRequest
	}
	return nil
}

func (m *ControlMessage) GetLocalStatusReportResponse() *LocalStatusReportResponse {
	if m != nil {
		return m.LocalStatusReportResponse
	}
	return nil
}

type StopResponse struct {
	StartRequestHash uint32 `protobuf:"varint,1,opt,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *StopResponse) Reset()                    { *m = StopResponse{} }
func (m *StopResponse) String() string            { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()               {}
func (*StopResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *StopResponse) GetStartRequestHash() uint32 {
	if m != nil {
		return m.StartRequestHash
	}
	return 0
}

func (m *StopResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetStatusRequest struct {
	StartRequestHash uint32 `protobuf:"varint,1,opt,name=startRequestHash" json:"startRequestHash,omitempty"`
}

func (m *GetStatusRequest) Reset()                    { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()               {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetStatusRequest) GetStartRequestHash() uint32 {
	if m != nil {
		return m.StartRequestHash
	}
	return 0
}

type ChannelStatus struct {
	Length    int64  `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
	StartTime int64  `protobuf:"varint,2,opt,name=startTime" json:"startTime,omitempty"`
	StopTime  int64  `protobuf:"varint,3,opt,name=stopTime" json:"stopTime,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *ChannelStatus) Reset()                    { *m = ChannelStatus{} }
func (m *ChannelStatus) String() string            { return proto.CompactTextString(m) }
func (*ChannelStatus) ProtoMessage()               {}
func (*ChannelStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ChannelStatus) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ChannelStatus) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ChannelStatus) GetStopTime() int64 {
	if m != nil {
		return m.StopTime
	}
	return 0
}

func (m *ChannelStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetStatusResponse struct {
	StartRequestHash uint32           `protobuf:"varint,1,opt,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            string           `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	InputStatuses    []*ChannelStatus `protobuf:"bytes,3,rep,name=inputStatuses" json:"inputStatuses,omitempty"`
	OutputStatuses   []*ChannelStatus `protobuf:"bytes,4,rep,name=outputStatuses" json:"outputStatuses,omitempty"`
	RequestTime      int64            `protobuf:"varint,5,opt,name=requestTime" json:"requestTime,omitempty"`
	StartTime        int64            `protobuf:"varint,6,opt,name=startTime" json:"startTime,omitempty"`
	StopTime         int64            `protobuf:"varint,7,opt,name=stopTime" json:"stopTime,omitempty"`
}

func (m *GetStatusResponse) Reset()                    { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()               {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetStatusResponse) GetStartRequestHash() uint32 {
	if m != nil {
		return m.StartRequestHash
	}
	return 0
}

func (m *GetStatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetStatusResponse) GetInputStatuses() []*ChannelStatus {
	if m != nil {
		return m.InputStatuses
	}
	return nil
}

func (m *GetStatusResponse) GetOutputStatuses() []*ChannelStatus {
	if m != nil {
		return m.OutputStatuses
	}
	return nil
}

func (m *GetStatusResponse) GetRequestTime() int64 {
	if m != nil {
		return m.RequestTime
	}
	return 0
}

func (m *GetStatusResponse) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GetStatusResponse) GetStopTime() int64 {
	if m != nil {
		return m.StopTime
	}
	return 0
}

type DeleteDatasetShardRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteDatasetShardRequest) Reset()                    { *m = DeleteDatasetShardRequest{} }
func (m *DeleteDatasetShardRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDatasetShardRequest) ProtoMessage()               {}
func (*DeleteDatasetShardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *DeleteDatasetShardRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteDatasetShardResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *DeleteDatasetShardResponse) Reset()                    { *m = DeleteDatasetShardResponse{} }
func (m *DeleteDatasetShardResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDatasetShardResponse) ProtoMessage()               {}
func (*DeleteDatasetShardResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DeleteDatasetShardResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LocalStatusReportRequest struct {
	StartRequestHash uint32           `protobuf:"varint,1,opt,name=startRequestHash" json:"startRequestHash,omitempty"`
	Error            string           `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	InputStatuses    []*ChannelStatus `protobuf:"bytes,3,rep,name=inputStatuses" json:"inputStatuses,omitempty"`
	OutputStatuses   []*ChannelStatus `protobuf:"bytes,4,rep,name=outputStatuses" json:"outputStatuses,omitempty"`
}

func (m *LocalStatusReportRequest) Reset()                    { *m = LocalStatusReportRequest{} }
func (m *LocalStatusReportRequest) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusReportRequest) ProtoMessage()               {}
func (*LocalStatusReportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *LocalStatusReportRequest) GetStartRequestHash() uint32 {
	if m != nil {
		return m.StartRequestHash
	}
	return 0
}

func (m *LocalStatusReportRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *LocalStatusReportRequest) GetInputStatuses() []*ChannelStatus {
	if m != nil {
		return m.InputStatuses
	}
	return nil
}

func (m *LocalStatusReportRequest) GetOutputStatuses() []*ChannelStatus {
	if m != nil {
		return m.OutputStatuses
	}
	return nil
}

type LocalStatusReportResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *LocalStatusReportResponse) Reset()                    { *m = LocalStatusReportResponse{} }
func (m *LocalStatusReportResponse) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusReportResponse) ProtoMessage()               {}
func (*LocalStatusReportResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *LocalStatusReportResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type WriteRequest struct {
	ChannelName string `protobuf:"bytes,1,opt,name=channelName" json:"channelName,omitempty"`
	WriterName  string `protobuf:"bytes,2,opt,name=writerName" json:"writerName,omitempty"`
	ReaderCount int32  `protobuf:"varint,3,opt,name=readerCount" json:"readerCount,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *WriteRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *WriteRequest) GetWriterName() string {
	if m != nil {
		return m.WriterName
	}
	return ""
}

func (m *WriteRequest) GetReaderCount() int32 {
	if m != nil {
		return m.ReaderCount
	}
	return 0
}

type ReadRequest struct {
	ChannelName string `protobuf:"bytes,1,opt,name=channelName" json:"channelName,omitempty"`
	ReaderName  string `protobuf:"bytes,2,opt,name=readerName" json:"readerName,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ReadRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *ReadRequest) GetReaderName() string {
	if m != nil {
		return m.ReaderName
	}
	return ""
}

type StopRequest struct {
	StartRequestHash uint32 `protobuf:"varint,1,opt,name=startRequestHash" json:"startRequestHash,omitempty"`
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *StopRequest) GetStartRequestHash() uint32 {
	if m != nil {
		return m.StartRequestHash
	}
	return 0
}

type InstructionSet struct {
	Instructions []*Instruction `protobuf:"bytes,1,rep,name=instructions" json:"instructions,omitempty"`
	ReaderCount  int32          `protobuf:"varint,2,opt,name=readerCount" json:"readerCount,omitempty"`
	FlowHashCode uint32         `protobuf:"varint,3,opt,name=flowHashCode" json:"flowHashCode,omitempty"`
	IsProfiling  bool           `protobuf:"varint,4,opt,name=isProfiling" json:"isProfiling,omitempty"`
}

func (m *InstructionSet) Reset()                    { *m = InstructionSet{} }
func (m *InstructionSet) String() string            { return proto.CompactTextString(m) }
func (*InstructionSet) ProtoMessage()               {}
func (*InstructionSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *InstructionSet) GetInstructions() []*Instruction {
	if m != nil {
		return m.Instructions
	}
	return nil
}

func (m *InstructionSet) GetReaderCount() int32 {
	if m != nil {
		return m.ReaderCount
	}
	return 0
}

func (m *InstructionSet) GetFlowHashCode() uint32 {
	if m != nil {
		return m.FlowHashCode
	}
	return 0
}

func (m *InstructionSet) GetIsProfiling() bool {
	if m != nil {
		return m.IsProfiling
	}
	return false
}

type Instruction struct {
	Name                     string                    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	InputShardLocations      []*DatasetShardLocation   `protobuf:"bytes,2,rep,name=inputShardLocations" json:"inputShardLocations,omitempty"`
	OutputShardLocations     []*DatasetShardLocation   `protobuf:"bytes,3,rep,name=OutputShardLocations,json=outputShardLocations" json:"OutputShardLocations,omitempty"`
	MemoryInMB               int32                     `protobuf:"varint,4,opt,name=memoryInMB" json:"memoryInMB,omitempty"`
	JoinPartitionedSorted    *JoinPartitionedSorted    `protobuf:"bytes,5,opt,name=joinPartitionedSorted" json:"joinPartitionedSorted,omitempty"`
	CoGroupPartitionedSorted *CoGroupPartitionedSorted `protobuf:"bytes,6,opt,name=coGroupPartitionedSorted" json:"coGroupPartitionedSorted,omitempty"`
	PipeAsArgs               *PipeAsArgs               `protobuf:"bytes,7,opt,name=pipeAsArgs" json:"pipeAsArgs,omitempty"`
	ScatterPartitions        *ScatterPartitions        `protobuf:"bytes,8,opt,name=scatterPartitions" json:"scatterPartitions,omitempty"`
	CollectPartitions        *CollectPartitions        `protobuf:"bytes,9,opt,name=collectPartitions" json:"collectPartitions,omitempty"`
	InputSplitReader         *InputSplitReader         `protobuf:"bytes,10,opt,name=inputSplitReader" json:"inputSplitReader,omitempty"`
	RoundRobin               *RoundRobin               `protobuf:"bytes,11,opt,name=roundRobin" json:"roundRobin,omitempty"`
	LocalTop                 *LocalTop                 `protobuf:"bytes,12,opt,name=localTop" json:"localTop,omitempty"`
	Broadcast                *Broadcast                `protobuf:"bytes,13,opt,name=broadcast" json:"broadcast,omitempty"`
	LocalHashAndJoinWith     *LocalHashAndJoinWith     `protobuf:"bytes,14,opt,name=localHashAndJoinWith" json:"localHashAndJoinWith,omitempty"`
	Script                   *Script                   `protobuf:"bytes,15,opt,name=script" json:"script,omitempty"`
	LocalSort                *LocalSort                `protobuf:"bytes,16,opt,name=localSort" json:"localSort,omitempty"`
	AdapterSplitReader       *AdapterSplitReader       `protobuf:"bytes,17,opt,name=adapterSplitReader" json:"adapterSplitReader,omitempty"`
	MergeSortedTo            *MergeSortedTo            `protobuf:"bytes,18,opt,name=mergeSortedTo" json:"mergeSortedTo,omitempty"`
}

func (m *Instruction) Reset()                    { *m = Instruction{} }
func (m *Instruction) String() string            { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()               {}
func (*Instruction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *Instruction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Instruction) GetInputShardLocations() []*DatasetShardLocation {
	if m != nil {
		return m.InputShardLocations
	}
	return nil
}

func (m *Instruction) GetOutputShardLocations() []*DatasetShardLocation {
	if m != nil {
		return m.OutputShardLocations
	}
	return nil
}

func (m *Instruction) GetMemoryInMB() int32 {
	if m != nil {
		return m.MemoryInMB
	}
	return 0
}

func (m *Instruction) GetJoinPartitionedSorted() *JoinPartitionedSorted {
	if m != nil {
		return m.JoinPartitionedSorted
	}
	return nil
}

func (m *Instruction) GetCoGroupPartitionedSorted() *CoGroupPartitionedSorted {
	if m != nil {
		return m.CoGroupPartitionedSorted
	}
	return nil
}

func (m *Instruction) GetPipeAsArgs() *PipeAsArgs {
	if m != nil {
		return m.PipeAsArgs
	}
	return nil
}

func (m *Instruction) GetScatterPartitions() *ScatterPartitions {
	if m != nil {
		return m.ScatterPartitions
	}
	return nil
}

func (m *Instruction) GetCollectPartitions() *CollectPartitions {
	if m != nil {
		return m.CollectPartitions
	}
	return nil
}

func (m *Instruction) GetInputSplitReader() *InputSplitReader {
	if m != nil {
		return m.InputSplitReader
	}
	return nil
}

func (m *Instruction) GetRoundRobin() *RoundRobin {
	if m != nil {
		return m.RoundRobin
	}
	return nil
}

func (m *Instruction) GetLocalTop() *LocalTop {
	if m != nil {
		return m.LocalTop
	}
	return nil
}

func (m *Instruction) GetBroadcast() *Broadcast {
	if m != nil {
		return m.Broadcast
	}
	return nil
}

func (m *Instruction) GetLocalHashAndJoinWith() *LocalHashAndJoinWith {
	if m != nil {
		return m.LocalHashAndJoinWith
	}
	return nil
}

func (m *Instruction) GetScript() *Script {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *Instruction) GetLocalSort() *LocalSort {
	if m != nil {
		return m.LocalSort
	}
	return nil
}

func (m *Instruction) GetAdapterSplitReader() *AdapterSplitReader {
	if m != nil {
		return m.AdapterSplitReader
	}
	return nil
}

func (m *Instruction) GetMergeSortedTo() *MergeSortedTo {
	if m != nil {
		return m.MergeSortedTo
	}
	return nil
}

type ScatterPartitions struct {
	Indexes []int32 `protobuf:"varint,1,rep,packed,name=indexes" json:"indexes,omitempty"`
}

func (m *ScatterPartitions) Reset()                    { *m = ScatterPartitions{} }
func (m *ScatterPartitions) String() string            { return proto.CompactTextString(m) }
func (*ScatterPartitions) ProtoMessage()               {}
func (*ScatterPartitions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ScatterPartitions) GetIndexes() []int32 {
	if m != nil {
		return m.Indexes
	}
	return nil
}

type RoundRobin struct {
}

func (m *RoundRobin) Reset()                    { *m = RoundRobin{} }
func (m *RoundRobin) String() string            { return proto.CompactTextString(m) }
func (*RoundRobin) ProtoMessage()               {}
func (*RoundRobin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

type CollectPartitions struct {
}

func (m *CollectPartitions) Reset()                    { *m = CollectPartitions{} }
func (m *CollectPartitions) String() string            { return proto.CompactTextString(m) }
func (*CollectPartitions) ProtoMessage()               {}
func (*CollectPartitions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type LocalSort struct {
	OrderBys []*OrderBy `protobuf:"bytes,1,rep,name=orderBys" json:"orderBys,omitempty"`
}

func (m *LocalSort) Reset()                    { *m = LocalSort{} }
func (m *LocalSort) String() string            { return proto.CompactTextString(m) }
func (*LocalSort) ProtoMessage()               {}
func (*LocalSort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *LocalSort) GetOrderBys() []*OrderBy {
	if m != nil {
		return m.OrderBys
	}
	return nil
}

type LocalTop struct {
	N        int32      `protobuf:"varint,1,opt,name=n" json:"n,omitempty"`
	OrderBys []*OrderBy `protobuf:"bytes,2,rep,name=orderBys" json:"orderBys,omitempty"`
}

func (m *LocalTop) Reset()                    { *m = LocalTop{} }
func (m *LocalTop) String() string            { return proto.CompactTextString(m) }
func (*LocalTop) ProtoMessage()               {}
func (*LocalTop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *LocalTop) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *LocalTop) GetOrderBys() []*OrderBy {
	if m != nil {
		return m.OrderBys
	}
	return nil
}

type MergeSortedTo struct {
	OrderBys []*OrderBy `protobuf:"bytes,1,rep,name=orderBys" json:"orderBys,omitempty"`
}

func (m *MergeSortedTo) Reset()                    { *m = MergeSortedTo{} }
func (m *MergeSortedTo) String() string            { return proto.CompactTextString(m) }
func (*MergeSortedTo) ProtoMessage()               {}
func (*MergeSortedTo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *MergeSortedTo) GetOrderBys() []*OrderBy {
	if m != nil {
		return m.OrderBys
	}
	return nil
}

type OrderBy struct {
	Index int32 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Order int32 `protobuf:"varint,2,opt,name=order" json:"order,omitempty"`
}

func (m *OrderBy) Reset()                    { *m = OrderBy{} }
func (m *OrderBy) String() string            { return proto.CompactTextString(m) }
func (*OrderBy) ProtoMessage()               {}
func (*OrderBy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *OrderBy) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *OrderBy) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

type JoinPartitionedSorted struct {
	Indexes          []int32 `protobuf:"varint,1,rep,packed,name=indexes" json:"indexes,omitempty"`
	IsLeftOuterJoin  bool    `protobuf:"varint,2,opt,name=isLeftOuterJoin" json:"isLeftOuterJoin,omitempty"`
	IsRightOuterJoin bool    `protobuf:"varint,3,opt,name=isRightOuterJoin" json:"isRightOuterJoin,omitempty"`
}

func (m *JoinPartitionedSorted) Reset()                    { *m = JoinPartitionedSorted{} }
func (m *JoinPartitionedSorted) String() string            { return proto.CompactTextString(m) }
func (*JoinPartitionedSorted) ProtoMessage()               {}
func (*JoinPartitionedSorted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *JoinPartitionedSorted) GetIndexes() []int32 {
	if m != nil {
		return m.Indexes
	}
	return nil
}

func (m *JoinPartitionedSorted) GetIsLeftOuterJoin() bool {
	if m != nil {
		return m.IsLeftOuterJoin
	}
	return false
}

func (m *JoinPartitionedSorted) GetIsRightOuterJoin() bool {
	if m != nil {
		return m.IsRightOuterJoin
	}
	return false
}

type CoGroupPartitionedSorted struct {
	Indexes []int32 `protobuf:"varint,1,rep,packed,name=indexes" json:"indexes,omitempty"`
}

func (m *CoGroupPartitionedSorted) Reset()                    { *m = CoGroupPartitionedSorted{} }
func (m *CoGroupPartitionedSorted) String() string            { return proto.CompactTextString(m) }
func (*CoGroupPartitionedSorted) ProtoMessage()               {}
func (*CoGroupPartitionedSorted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *CoGroupPartitionedSorted) GetIndexes() []int32 {
	if m != nil {
		return m.Indexes
	}
	return nil
}

type PipeAsArgs struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
}

func (m *PipeAsArgs) Reset()                    { *m = PipeAsArgs{} }
func (m *PipeAsArgs) String() string            { return proto.CompactTextString(m) }
func (*PipeAsArgs) ProtoMessage()               {}
func (*PipeAsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *PipeAsArgs) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Script struct {
	IsPipe bool     `protobuf:"varint,1,opt,name=isPipe" json:"isPipe,omitempty"`
	Path   string   `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Args   []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	Env    []string `protobuf:"bytes,4,rep,name=env" json:"env,omitempty"`
}

func (m *Script) Reset()                    { *m = Script{} }
func (m *Script) String() string            { return proto.CompactTextString(m) }
func (*Script) ProtoMessage()               {}
func (*Script) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *Script) GetIsPipe() bool {
	if m != nil {
		return m.IsPipe
	}
	return false
}

func (m *Script) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Script) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Script) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

type InputSplitReader struct {
	InputType string `protobuf:"bytes,1,opt,name=inputType" json:"inputType,omitempty"`
}

func (m *InputSplitReader) Reset()                    { *m = InputSplitReader{} }
func (m *InputSplitReader) String() string            { return proto.CompactTextString(m) }
func (*InputSplitReader) ProtoMessage()               {}
func (*InputSplitReader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *InputSplitReader) GetInputType() string {
	if m != nil {
		return m.InputType
	}
	return ""
}

type AdapterSplitReader struct {
	AdapterName  string `protobuf:"bytes,1,opt,name=adapterName" json:"adapterName,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connectionId" json:"connectionId,omitempty"`
}

func (m *AdapterSplitReader) Reset()                    { *m = AdapterSplitReader{} }
func (m *AdapterSplitReader) String() string            { return proto.CompactTextString(m) }
func (*AdapterSplitReader) ProtoMessage()               {}
func (*AdapterSplitReader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *AdapterSplitReader) GetAdapterName() string {
	if m != nil {
		return m.AdapterName
	}
	return ""
}

func (m *AdapterSplitReader) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

type Broadcast struct {
}

func (m *Broadcast) Reset()                    { *m = Broadcast{} }
func (m *Broadcast) String() string            { return proto.CompactTextString(m) }
func (*Broadcast) ProtoMessage()               {}
func (*Broadcast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

type LocalHashAndJoinWith struct {
	Indexes []int32 `protobuf:"varint,1,rep,packed,name=indexes" json:"indexes,omitempty"`
}

func (m *LocalHashAndJoinWith) Reset()                    { *m = LocalHashAndJoinWith{} }
func (m *LocalHashAndJoinWith) String() string            { return proto.CompactTextString(m) }
func (*LocalHashAndJoinWith) ProtoMessage()               {}
func (*LocalHashAndJoinWith) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *LocalHashAndJoinWith) GetIndexes() []int32 {
	if m != nil {
		return m.Indexes
	}
	return nil
}

type DatasetShard struct {
	FlowName       string `protobuf:"bytes,1,opt,name=FlowName,json=flowName" json:"FlowName,omitempty"`
	DatasetId      int32  `protobuf:"varint,2,opt,name=DatasetId,json=datasetId" json:"DatasetId,omitempty"`
	DatasetShardId int32  `protobuf:"varint,3,opt,name=DatasetShardId,json=datasetShardId" json:"DatasetShardId,omitempty"`
	FlowHashCode   uint32 `protobuf:"varint,4,opt,name=FlowHashCode,json=flowHashCode" json:"FlowHashCode,omitempty"`
}

func (m *DatasetShard) Reset()                    { *m = DatasetShard{} }
func (m *DatasetShard) String() string            { return proto.CompactTextString(m) }
func (*DatasetShard) ProtoMessage()               {}
func (*DatasetShard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *DatasetShard) GetFlowName() string {
	if m != nil {
		return m.FlowName
	}
	return ""
}

func (m *DatasetShard) GetDatasetId() int32 {
	if m != nil {
		return m.DatasetId
	}
	return 0
}

func (m *DatasetShard) GetDatasetShardId() int32 {
	if m != nil {
		return m.DatasetShardId
	}
	return 0
}

func (m *DatasetShard) GetFlowHashCode() uint32 {
	if m != nil {
		return m.FlowHashCode
	}
	return 0
}

type DatasetShardLocation struct {
	Name   string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Host   string `protobuf:"bytes,2,opt,name=Host,json=host" json:"Host,omitempty"`
	Port   int32  `protobuf:"varint,3,opt,name=Port,json=port" json:"Port,omitempty"`
	OnDisk bool   `protobuf:"varint,4,opt,name=onDisk" json:"onDisk,omitempty"`
}

func (m *DatasetShardLocation) Reset()                    { *m = DatasetShardLocation{} }
func (m *DatasetShardLocation) String() string            { return proto.CompactTextString(m) }
func (*DatasetShardLocation) ProtoMessage()               {}
func (*DatasetShardLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *DatasetShardLocation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DatasetShardLocation) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DatasetShardLocation) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *DatasetShardLocation) GetOnDisk() bool {
	if m != nil {
		return m.OnDisk
	}
	return false
}

func init() {
	proto.RegisterType((*ComputeRequest)(nil), "pb.ComputeRequest")
	proto.RegisterType((*ComputeResource)(nil), "pb.ComputeResource")
	proto.RegisterType((*DataResource)(nil), "pb.DataResource")
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*Allocation)(nil), "pb.Allocation")
	proto.RegisterType((*AllocationResult)(nil), "pb.AllocationResult")
	proto.RegisterType((*Heartbeat)(nil), "pb.Heartbeat")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*DataLocation)(nil), "pb.DataLocation")
	proto.RegisterType((*ExecutionRequest)(nil), "pb.ExecutionRequest")
	proto.RegisterType((*ExecutionResponse)(nil), "pb.ExecutionResponse")
	proto.RegisterType((*ControlMessage)(nil), "pb.ControlMessage")
	proto.RegisterType((*StopResponse)(nil), "pb.StopResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "pb.GetStatusRequest")
	proto.RegisterType((*ChannelStatus)(nil), "pb.ChannelStatus")
	proto.RegisterType((*GetStatusResponse)(nil), "pb.GetStatusResponse")
	proto.RegisterType((*DeleteDatasetShardRequest)(nil), "pb.DeleteDatasetShardRequest")
	proto.RegisterType((*DeleteDatasetShardResponse)(nil), "pb.DeleteDatasetShardResponse")
	proto.RegisterType((*LocalStatusReportRequest)(nil), "pb.LocalStatusReportRequest")
	proto.RegisterType((*LocalStatusReportResponse)(nil), "pb.LocalStatusReportResponse")
	proto.RegisterType((*WriteRequest)(nil), "pb.WriteRequest")
	proto.RegisterType((*ReadRequest)(nil), "pb.ReadRequest")
	proto.RegisterType((*StopRequest)(nil), "pb.StopRequest")
	proto.RegisterType((*InstructionSet)(nil), "pb.InstructionSet")
	proto.RegisterType((*Instruction)(nil), "pb.Instruction")
	proto.RegisterType((*ScatterPartitions)(nil), "pb.ScatterPartitions")
	proto.RegisterType((*RoundRobin)(nil), "pb.RoundRobin")
	proto.RegisterType((*CollectPartitions)(nil), "pb.CollectPartitions")
	proto.RegisterType((*LocalSort)(nil), "pb.LocalSort")
	proto.RegisterType((*LocalTop)(nil), "pb.LocalTop")
	proto.RegisterType((*MergeSortedTo)(nil), "pb.MergeSortedTo")
	proto.RegisterType((*OrderBy)(nil), "pb.OrderBy")
	proto.RegisterType((*JoinPartitionedSorted)(nil), "pb.JoinPartitionedSorted")
	proto.RegisterType((*CoGroupPartitionedSorted)(nil), "pb.CoGroupPartitionedSorted")
	proto.RegisterType((*PipeAsArgs)(nil), "pb.PipeAsArgs")
	proto.RegisterType((*Script)(nil), "pb.Script")
	proto.RegisterType((*InputSplitReader)(nil), "pb.InputSplitReader")
	proto.RegisterType((*AdapterSplitReader)(nil), "pb.AdapterSplitReader")
	proto.RegisterType((*Broadcast)(nil), "pb.Broadcast")
	proto.RegisterType((*LocalHashAndJoinWith)(nil), "pb.LocalHashAndJoinWith")
	proto.RegisterType((*DatasetShard)(nil), "pb.DatasetShard")
	proto.RegisterType((*DatasetShardLocation)(nil), "pb.DatasetShardLocation")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GleamMaster service

type GleamMasterClient interface {
	GetResources(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*AllocationResult, error)
	SendHeartbeat(ctx context.Context, opts ...grpc.CallOption) (GleamMaster_SendHeartbeatClient, error)
}

type gleamMasterClient struct {
	cc *grpc.ClientConn
}

func NewGleamMasterClient(cc *grpc.ClientConn) GleamMasterClient {
	return &gleamMasterClient{cc}
}

func (c *gleamMasterClient) GetResources(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*AllocationResult, error) {
	out := new(AllocationResult)
	err := grpc.Invoke(ctx, "/pb.GleamMaster/GetResources", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gleamMasterClient) SendHeartbeat(ctx context.Context, opts ...grpc.CallOption) (GleamMaster_SendHeartbeatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GleamMaster_serviceDesc.Streams[0], c.cc, "/pb.GleamMaster/SendHeartbeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &gleamMasterSendHeartbeatClient{stream}
	return x, nil
}

type GleamMaster_SendHeartbeatClient interface {
	Send(*Heartbeat) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type gleamMasterSendHeartbeatClient struct {
	grpc.ClientStream
}

func (x *gleamMasterSendHeartbeatClient) Send(m *Heartbeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gleamMasterSendHeartbeatClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GleamMaster service

type GleamMasterServer interface {
	GetResources(context.Context, *ComputeRequest) (*AllocationResult, error)
	SendHeartbeat(GleamMaster_SendHeartbeatServer) error
}

func RegisterGleamMasterServer(s *grpc.Server, srv GleamMasterServer) {
	s.RegisterService(&_GleamMaster_serviceDesc, srv)
}

func _GleamMaster_GetResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GleamMasterServer).GetResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GleamMaster/GetResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GleamMasterServer).GetResources(ctx, req.(*ComputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GleamMaster_SendHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GleamMasterServer).SendHeartbeat(&gleamMasterSendHeartbeatServer{stream})
}

type GleamMaster_SendHeartbeatServer interface {
	SendAndClose(*Empty) error
	Recv() (*Heartbeat, error)
	grpc.ServerStream
}

type gleamMasterSendHeartbeatServer struct {
	grpc.ServerStream
}

func (x *gleamMasterSendHeartbeatServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gleamMasterSendHeartbeatServer) Recv() (*Heartbeat, error) {
	m := new(Heartbeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GleamMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GleamMaster",
	HandlerType: (*GleamMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResources",
			Handler:    _GleamMaster_GetResources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendHeartbeat",
			Handler:       _GleamMaster_SendHeartbeat_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "master_agent.proto",
}

// Client API for GleamAgent service

type GleamAgentClient interface {
	Execute(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (GleamAgent_ExecuteClient, error)
	Delete(ctx context.Context, in *DeleteDatasetShardRequest, opts ...grpc.CallOption) (*DeleteDatasetShardResponse, error)
}

type gleamAgentClient struct {
	cc *grpc.ClientConn
}

func NewGleamAgentClient(cc *grpc.ClientConn) GleamAgentClient {
	return &gleamAgentClient{cc}
}

func (c *gleamAgentClient) Execute(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (GleamAgent_ExecuteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GleamAgent_serviceDesc.Streams[0], c.cc, "/pb.GleamAgent/Execute", opts...)
	if err != nil {
		return nil, err
	}
	x := &gleamAgentExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GleamAgent_ExecuteClient interface {
	Recv() (*ExecutionResponse, error)
	grpc.ClientStream
}

type gleamAgentExecuteClient struct {
	grpc.ClientStream
}

func (x *gleamAgentExecuteClient) Recv() (*ExecutionResponse, error) {
	m := new(ExecutionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gleamAgentClient) Delete(ctx context.Context, in *DeleteDatasetShardRequest, opts ...grpc.CallOption) (*DeleteDatasetShardResponse, error) {
	out := new(DeleteDatasetShardResponse)
	err := grpc.Invoke(ctx, "/pb.GleamAgent/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GleamAgent service

type GleamAgentServer interface {
	Execute(*ExecutionRequest, GleamAgent_ExecuteServer) error
	Delete(context.Context, *DeleteDatasetShardRequest) (*DeleteDatasetShardResponse, error)
}

func RegisterGleamAgentServer(s *grpc.Server, srv GleamAgentServer) {
	s.RegisterService(&_GleamAgent_serviceDesc, srv)
}

func _GleamAgent_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecutionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GleamAgentServer).Execute(m, &gleamAgentExecuteServer{stream})
}

type GleamAgent_ExecuteServer interface {
	Send(*ExecutionResponse) error
	grpc.ServerStream
}

type gleamAgentExecuteServer struct {
	grpc.ServerStream
}

func (x *gleamAgentExecuteServer) Send(m *ExecutionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GleamAgent_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatasetShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GleamAgentServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GleamAgent/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GleamAgentServer).Delete(ctx, req.(*DeleteDatasetShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GleamAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GleamAgent",
	HandlerType: (*GleamAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _GleamAgent_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _GleamAgent_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "master_agent.proto",
}

func init() { proto.RegisterFile("master_agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1848 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x18, 0xcb, 0x72, 0xdc, 0xb8,
	0xd1, 0xa3, 0x19, 0x8d, 0x86, 0x3d, 0x23, 0x79, 0x04, 0xcb, 0x0e, 0xad, 0x6c, 0x36, 0x2a, 0x1c,
	0x12, 0x55, 0x52, 0xeb, 0xb5, 0xb5, 0xce, 0x63, 0xf7, 0x90, 0x5a, 0x79, 0xbc, 0xb6, 0xb5, 0x25,
	0xad, 0x54, 0x90, 0xab, 0x36, 0xb5, 0x39, 0xa8, 0x38, 0x24, 0x34, 0xe2, 0x9a, 0x43, 0x32, 0x00,
	0xe8, 0x47, 0x7e, 0x20, 0x1f, 0x90, 0x5c, 0xf2, 0x01, 0x39, 0xe4, 0x90, 0x2f, 0xc8, 0x25, 0x9f,
	0x90, 0x3f, 0xc8, 0xaf, 0xa4, 0x1a, 0x00, 0x49, 0x90, 0x33, 0x23, 0xcb, 0x95, 0xd3, 0xde, 0x80,
	0x7e, 0x77, 0xa3, 0xd1, 0xdd, 0x00, 0x90, 0x79, 0x20, 0x15, 0x17, 0x17, 0xc1, 0x8c, 0xa7, 0xea,
	0x41, 0x2e, 0x32, 0x95, 0x91, 0xb5, 0x7c, 0x4a, 0x25, 0x6c, 0x4d, 0xb2, 0x79, 0x5e, 0x28, 0xce,
	0xf8, 0x1f, 0x0b, 0x2e, 0x15, 0xf9, 0x29, 0x0c, 0xa3, 0x40, 0x05, 0x17, 0x21, 0x4f, 0x15, 0x17,
	0x7e, 0x67, 0xaf, 0xb3, 0xef, 0x31, 0x40, 0xd0, 0x44, 0x43, 0xc8, 0x97, 0xb0, 0x1d, 0x1a, 0x96,
	0x0b, 0xc1, 0x65, 0x56, 0x88, 0x90, 0x4b, 0x7f, 0x6d, 0xaf, 0xbb, 0x3f, 0x3c, 0xb8, 0xf3, 0x20,
	0x9f, 0x3e, 0xa8, 0xe4, 0x19, 0x1c, 0x1b, 0x87, 0x4d, 0x80, 0xa4, 0xff, 0xea, 0xc0, 0xed, 0x16,
	0x15, 0xf9, 0x31, 0x78, 0x61, 0x5e, 0x5c, 0x84, 0x59, 0x91, 0x2a, 0xad, 0x74, 0x9d, 0x0d, 0xc2,
	0xbc, 0x98, 0xe0, 0xbe, 0x44, 0x26, 0xfc, 0x35, 0x4f, 0xfc, 0xb5, 0x0a, 0x79, 0x8c, 0x7b, 0x44,
	0xce, 0x2a, 0xce, 0xae, 0x41, 0xce, 0x1c, 0xce, 0x59, 0xc5, 0xd9, 0xab, 0x90, 0x15, 0xe7, 0x9c,
	0xcf, 0x33, 0xf1, 0xee, 0x62, 0x3e, 0xf5, 0xd7, 0xf7, 0x3a, 0xfb, 0x5d, 0x36, 0x30, 0x80, 0x93,
	0x29, 0xf9, 0x11, 0x6c, 0x44, 0xb1, 0x7c, 0x85, 0xa8, 0xbe, 0x46, 0xf5, 0x71, 0x7b, 0x32, 0xa5,
	0xc7, 0x30, 0x7a, 0x1a, 0xa8, 0xa0, 0xb2, 0x7c, 0x1f, 0x06, 0x49, 0x16, 0x06, 0x2a, 0xce, 0x52,
	0x6d, 0xf8, 0xf0, 0x60, 0x84, 0x61, 0x38, 0xb6, 0x30, 0x56, 0x61, 0x09, 0x81, 0x9e, 0x8c, 0xff,
	0xc4, 0xb5, 0x07, 0x5d, 0xa6, 0xd7, 0xf4, 0x15, 0x0c, 0x4a, 0xca, 0xf7, 0x87, 0x9e, 0x40, 0x4f,
	0x04, 0xe1, 0x2b, 0x2d, 0xc0, 0x63, 0x7a, 0x4d, 0xee, 0x41, 0x5f, 0x72, 0xf1, 0x9a, 0x0b, 0xed,
	0xbb, 0xc7, 0xec, 0x0e, 0x69, 0xf3, 0x4c, 0x28, 0xeb, 0xb4, 0x5e, 0xd3, 0x18, 0xe0, 0x30, 0xa9,
	0xcc, 0xb9, 0xb9, 0xe1, 0x8f, 0xc0, 0x0b, 0x0c, 0x1f, 0x8f, 0xb4, 0xf2, 0x15, 0x47, 0x5d, 0x53,
	0xd1, 0xa7, 0x30, 0xae, 0x55, 0x31, 0x2e, 0x8b, 0x44, 0x91, 0x87, 0x30, 0x0c, 0x2a, 0x98, 0xf4,
	0x3b, 0x3a, 0x67, 0xb6, 0x50, 0x90, 0x43, 0xea, 0x92, 0xd0, 0xbf, 0x75, 0xc0, 0x7b, 0xc1, 0x03,
	0xa1, 0xa6, 0x3c, 0x50, 0x1f, 0x60, 0xf0, 0xa7, 0x30, 0x28, 0x73, 0xf3, 0x3a, 0x7b, 0x2b, 0xa2,
	0xa6, 0x87, 0xdd, 0x1b, 0x79, 0xb8, 0x01, 0xeb, 0x5f, 0xcd, 0x73, 0xf5, 0x8e, 0x46, 0x26, 0x21,
	0x8e, 0x9d, 0x63, 0x4e, 0x83, 0x39, 0xb7, 0xe7, 0xa7, 0xd7, 0x0d, 0xd3, 0xd7, 0xae, 0x35, 0xfd,
	0x1e, 0xf4, 0xb3, 0xf4, 0x69, 0x2c, 0x5f, 0x69, 0x33, 0x06, 0xcc, 0xee, 0xe8, 0x7f, 0x3b, 0x30,
	0xfe, 0xea, 0x2d, 0x0f, 0x0b, 0x13, 0x50, 0x73, 0x59, 0x7f, 0x0d, 0xa3, 0x38, 0x95, 0x4a, 0x14,
	0x61, 0x19, 0x52, 0x14, 0x4d, 0x50, 0xf4, 0x51, 0x0d, 0x3f, 0xe7, 0x8a, 0x35, 0xe8, 0xc8, 0x0e,
	0xac, 0x5f, 0xc6, 0x89, 0xbd, 0xb7, 0x1e, 0x33, 0x1b, 0x32, 0x86, 0x6e, 0x14, 0x97, 0x79, 0x84,
	0xcb, 0x46, 0x1c, 0x7b, 0x37, 0x89, 0x63, 0xe9, 0xfb, 0xba, 0xe3, 0x3b, 0x81, 0xde, 0x55, 0x26,
	0x95, 0xbe, 0x46, 0x1e, 0xd3, 0xeb, 0x2a, 0x3b, 0x37, 0x9c, 0xec, 0x3c, 0x84, 0x6d, 0xc7, 0x41,
	0x99, 0x67, 0xa9, 0xe4, 0x3a, 0x1c, 0x85, 0xca, 0x0b, 0x53, 0x14, 0x46, 0xcc, 0xee, 0xd0, 0x03,
	0x2e, 0x44, 0x26, 0x74, 0x34, 0x47, 0xcc, 0x6c, 0xe8, 0xbf, 0x7b, 0x58, 0xcf, 0x52, 0x25, 0xb2,
	0xe4, 0x84, 0x4b, 0x19, 0xcc, 0x38, 0xf9, 0x18, 0x20, 0x96, 0xa7, 0x3a, 0x86, 0x47, 0xa7, 0x5a,
	0xc8, 0x80, 0x39, 0x10, 0xf2, 0x08, 0x86, 0x82, 0x07, 0x91, 0x8d, 0xa8, 0x3d, 0x9c, 0xdb, 0xe8,
	0x25, 0xab, 0xc1, 0xcc, 0xa5, 0x21, 0x8f, 0x61, 0xf4, 0x46, 0xc4, 0x55, 0xc9, 0xb4, 0xf9, 0x32,
	0x46, 0x9e, 0x6f, 0x1d, 0x38, 0x6b, 0x50, 0xa1, 0x22, 0xa9, 0xb2, 0xbc, 0x64, 0xea, 0xd5, 0x8a,
	0xce, 0x6b, 0x30, 0x73, 0x69, 0x50, 0x91, 0xd9, 0x9a, 0x60, 0xe8, 0xa8, 0x5a, 0x45, 0xe7, 0x0e,
	0x9c, 0x35, 0xa8, 0xc8, 0x97, 0x30, 0x9e, 0x71, 0x75, 0xae, 0x02, 0x55, 0xc8, 0x52, 0x5b, 0x5f,
	0x73, 0xee, 0x20, 0xe7, 0xf3, 0x16, 0x8e, 0x2d, 0x50, 0x93, 0x09, 0x6c, 0x3b, 0x30, 0xab, 0x7c,
	0x43, 0x8b, 0xb8, 0xdb, 0x12, 0x61, 0x2d, 0x58, 0xa4, 0x27, 0xbf, 0x07, 0x1f, 0x93, 0x3a, 0x29,
	0xc1, 0x78, 0xc6, 0xa5, 0x39, 0x03, 0x2d, 0xeb, 0xa3, 0xf2, 0x0a, 0x2c, 0xa3, 0x61, 0x2b, 0xb9,
	0xc9, 0x1f, 0xe0, 0xfe, 0x12, 0x9c, 0x35, 0xd3, 0xd3, 0xa2, 0x7f, 0xb2, 0x42, 0xb4, 0x35, 0x77,
	0x35, 0x3f, 0x3d, 0x83, 0x91, 0x1b, 0x5b, 0xf2, 0x0b, 0x18, 0x4b, 0x15, 0x54, 0xca, 0x5f, 0x04,
	0xf2, 0x4a, 0x67, 0xd1, 0x26, 0x5b, 0x80, 0x37, 0x93, 0xd2, 0x2b, 0x93, 0xf2, 0x77, 0x30, 0x6e,
	0xc7, 0xfc, 0x43, 0xa4, 0xd2, 0x02, 0x36, 0x27, 0x57, 0x41, 0x9a, 0x72, 0x6b, 0x30, 0xde, 0x89,
	0x84, 0xa7, 0x33, 0x65, 0x58, 0xba, 0xcc, 0xee, 0xc8, 0x47, 0xe0, 0x69, 0xe6, 0x97, 0xf1, 0xbc,
	0x6c, 0x32, 0x35, 0x80, 0xec, 0xc2, 0x00, 0xd3, 0x44, 0x23, 0xbb, 0xa6, 0xd9, 0x95, 0xfb, 0xea,
	0xda, 0xf6, 0xea, 0x6b, 0x4b, 0xff, 0xbe, 0x06, 0xdb, 0x0b, 0x07, 0xfd, 0xff, 0x87, 0x83, 0xfc,
	0x06, 0x36, 0xe3, 0x34, 0x2f, 0xac, 0x60, 0x2e, 0xfd, 0xae, 0xee, 0x03, 0xdb, 0xba, 0xb0, 0xb8,
	0x7e, 0xb2, 0x26, 0x1d, 0xf9, 0x1c, 0xb6, 0xcc, 0xe5, 0xaf, 0x38, 0x7b, 0xab, 0x38, 0x5b, 0x84,
	0x64, 0x0f, 0x2f, 0xb9, 0x36, 0x4c, 0xbb, 0x6f, 0x7a, 0xbd, 0x0b, 0x6a, 0xc6, 0xae, 0x7f, 0x5d,
	0xec, 0x36, 0x9a, 0xb1, 0xa3, 0x9f, 0xc2, 0xfd, 0xa7, 0x3c, 0xe1, 0x8a, 0x63, 0x13, 0x90, 0x5c,
	0x9d, 0x5f, 0x05, 0xa2, 0x2a, 0x15, 0x4b, 0x7a, 0x01, 0x3d, 0x80, 0xdd, 0x65, 0x0c, 0x36, 0xc0,
	0x55, 0xd0, 0x3a, 0x6e, 0x0e, 0xfd, 0xa7, 0x03, 0xfe, 0xaa, 0x9b, 0xf2, 0xc3, 0x3c, 0x13, 0xfa,
	0x08, 0xee, 0xaf, 0xbc, 0xa0, 0x2b, 0xa2, 0x20, 0x60, 0xe4, 0x16, 0x58, 0x3c, 0xd6, 0xd0, 0xe8,
	0xf8, 0xa6, 0x0e, 0xb2, 0x0b, 0xc2, 0xea, 0xaf, 0x8b, 0xb0, 0xd0, 0x04, 0xc6, 0x67, 0x07, 0x62,
	0x12, 0x23, 0x88, 0xb8, 0x98, 0x38, 0xe3, 0xa3, 0x0b, 0xa2, 0xa7, 0x30, 0x74, 0x1a, 0xc1, 0xcd,
	0x54, 0x1a, 0x7e, 0x57, 0x65, 0x0d, 0xa1, 0x9f, 0xc3, 0xd0, 0x29, 0xf8, 0x1f, 0x54, 0x09, 0xfe,
	0xd9, 0x81, 0xad, 0x66, 0x5f, 0x27, 0x9f, 0x2d, 0x4c, 0x00, 0xdd, 0xb2, 0xad, 0x38, 0x94, 0xad,
	0xf6, 0xdf, 0xf2, 0x7a, 0x6d, 0xc1, 0x6b, 0x42, 0x61, 0x74, 0x99, 0x64, 0x6f, 0x50, 0xeb, 0x24,
	0x8b, 0x4c, 0xc1, 0xd8, 0x64, 0x0d, 0x18, 0x4a, 0x89, 0xe5, 0x99, 0xc8, 0x2e, 0xe3, 0x24, 0x4e,
	0x67, 0xba, 0x76, 0x0c, 0x98, 0x0b, 0xa2, 0xff, 0x18, 0xc0, 0xd0, 0xb1, 0x62, 0xe9, 0x64, 0xf4,
	0x35, 0xdc, 0x31, 0x29, 0x85, 0xb7, 0xe0, 0xb8, 0x1a, 0x0e, 0xcd, 0x83, 0xc2, 0x47, 0x3f, 0xdc,
	0x6b, 0x52, 0x0d, 0x4c, 0xcb, 0x98, 0xc8, 0x31, 0xec, 0x9c, 0x9a, 0x24, 0x6b, 0x0a, 0xeb, 0xbe,
	0x47, 0xd8, 0x4e, 0xb6, 0x84, 0x0b, 0x0f, 0xd2, 0xbc, 0x06, 0x8e, 0xd2, 0x93, 0x27, 0x76, 0x8e,
	0x76, 0x20, 0xe4, 0x14, 0xee, 0x7e, 0x9f, 0xc5, 0xe9, 0x59, 0x20, 0x54, 0x8c, 0x1c, 0x3c, 0x3a,
	0xcf, 0x04, 0xce, 0x8f, 0xa6, 0x4d, 0xdf, 0x47, 0x75, 0x5f, 0x2f, 0x23, 0x60, 0xcb, 0xf9, 0xb0,
	0x63, 0x86, 0xd9, 0x73, 0x91, 0x15, 0xf9, 0xa2, 0xcc, 0x7e, 0xdd, 0x31, 0x27, 0x2b, 0x68, 0xd8,
	0x4a, 0x6e, 0xf2, 0x00, 0x20, 0x8f, 0x73, 0x7e, 0x28, 0x0f, 0xc5, 0x4c, 0xda, 0x4e, 0xae, 0x07,
	0xef, 0xb3, 0x0a, 0xca, 0x1c, 0x0a, 0x1c, 0x00, 0x64, 0x18, 0x28, 0xc5, 0x45, 0x25, 0x4b, 0xda,
	0xa6, 0xad, 0x07, 0x80, 0xf3, 0x36, 0x92, 0x2d, 0xd2, 0xa3, 0x90, 0x30, 0x4b, 0x12, 0x1e, 0x2a,
	0x47, 0x88, 0x57, 0x0b, 0x99, 0xb4, 0x91, 0x6c, 0x91, 0x1e, 0x87, 0x19, 0x73, 0xd2, 0x79, 0x12,
	0x2b, 0xa6, 0x33, 0xd4, 0x87, 0x7a, 0x98, 0x39, 0x6a, 0xe1, 0xd8, 0x02, 0x35, 0xfa, 0x2e, 0xb2,
	0x22, 0x8d, 0x58, 0x36, 0x8d, 0x53, 0x7f, 0x58, 0xfb, 0xce, 0x2a, 0x28, 0x73, 0x28, 0xca, 0x51,
	0x3d, 0x79, 0x99, 0xe5, 0xfe, 0xa8, 0x39, 0xaa, 0x23, 0x8c, 0x55, 0x58, 0xf2, 0x4b, 0xf0, 0xa6,
	0x22, 0x0b, 0xa2, 0x30, 0x90, 0xca, 0xdf, 0xd4, 0xa4, 0x9b, 0x48, 0xfa, 0xa4, 0x04, 0xb2, 0x1a,
	0x8f, 0xb9, 0xa9, 0x19, 0xf1, 0xfa, 0x1c, 0xa6, 0x11, 0x26, 0xc6, 0xb7, 0xb1, 0xba, 0xf2, 0xb7,
	0x34, 0x9f, 0x5f, 0xa9, 0x68, 0xe1, 0xd9, 0x52, 0x2e, 0x42, 0xa1, 0x2f, 0x43, 0x11, 0xe7, 0xca,
	0xbf, 0xad, 0xf9, 0xc1, 0x9c, 0x0a, 0x42, 0x98, 0xc5, 0xa0, 0x79, 0x66, 0xcc, 0xc1, 0x41, 0x7b,
	0x5c, 0x9b, 0x77, 0x5c, 0x02, 0x59, 0x8d, 0x27, 0xcf, 0x80, 0x04, 0x51, 0x90, 0x2b, 0x2e, 0xdc,
	0x48, 0x6f, 0x6b, 0xae, 0x7b, 0xfa, 0x89, 0xb6, 0x80, 0x65, 0x4b, 0x38, 0xb0, 0x93, 0xcc, 0xb9,
	0x98, 0x71, 0x93, 0x78, 0x2f, 0x33, 0x9f, 0x68, 0x11, 0xba, 0x1f, 0x9c, 0xb8, 0x08, 0xd6, 0xa4,
	0xa3, 0x9f, 0xc0, 0xf6, 0x42, 0x56, 0x11, 0x1f, 0x36, 0xe2, 0x34, 0xe2, 0x6f, 0xb9, 0x29, 0x6c,
	0xeb, 0xac, 0xdc, 0xd2, 0x11, 0x40, 0x7d, 0x7e, 0xf4, 0x0e, 0x6c, 0x2f, 0x64, 0x13, 0x7d, 0x0c,
	0x5e, 0xe5, 0x2a, 0xf9, 0x39, 0x0c, 0x32, 0x11, 0x71, 0xf1, 0xe4, 0x5d, 0x59, 0x23, 0x87, 0x68,
	0xd2, 0xa9, 0x81, 0xb1, 0x0a, 0x49, 0x0f, 0xcd, 0x83, 0x5c, 0x1f, 0xf0, 0x08, 0x3a, 0xa9, 0xfd,
	0x8c, 0xe8, 0xa4, 0x0d, 0x11, 0x6b, 0xd7, 0x89, 0xf8, 0x2d, 0x6c, 0x36, 0x5c, 0xbd, 0xb9, 0xf2,
	0x5f, 0xc1, 0x86, 0x05, 0x62, 0x07, 0xd4, 0xbe, 0x5a, 0xfd, 0x66, 0x83, 0x50, 0x4d, 0x6c, 0x6b,
	0xb6, 0xd9, 0xd0, 0x3f, 0x77, 0xe0, 0xee, 0xd2, 0x4a, 0xb3, 0x3a, 0x80, 0x64, 0x1f, 0x6e, 0xc7,
	0xf2, 0x98, 0x5f, 0xaa, 0xd3, 0x42, 0x71, 0x81, 0xdc, 0x5a, 0xe6, 0x80, 0xb5, 0xc1, 0xd8, 0xa1,
	0x62, 0xc9, 0xe2, 0xd9, 0x95, 0x43, 0x6a, 0xde, 0xa6, 0x0b, 0x70, 0xfa, 0x18, 0xfc, 0x55, 0xe5,
	0xe9, 0x9a, 0xc3, 0xdc, 0x03, 0xa8, 0x0b, 0x11, 0x76, 0x89, 0x10, 0x7b, 0x8e, 0xed, 0x12, 0xb8,
	0xa6, 0xdf, 0x41, 0xdf, 0x64, 0x37, 0x0e, 0xbf, 0xb1, 0x44, 0x6a, 0xfb, 0x96, 0xb3, 0x3b, 0xfd,
	0xa2, 0x0c, 0xd4, 0x55, 0xf9, 0x37, 0x82, 0x6b, 0x84, 0x05, 0x58, 0xf0, 0xba, 0xfa, 0x95, 0xab,
	0xd7, 0xf8, 0xc8, 0xe5, 0xe9, 0x6b, 0x3d, 0xa6, 0x78, 0x0c, 0x97, 0xf4, 0x21, 0x8c, 0xdb, 0x65,
	0x04, 0xc7, 0x41, 0x5d, 0x48, 0x5e, 0xbe, 0xcb, 0x4b, 0x43, 0x6a, 0x00, 0xfd, 0x0e, 0xc8, 0xe2,
	0x75, 0xc0, 0x7e, 0x68, 0x2f, 0x84, 0x3b, 0x1a, 0x38, 0x20, 0xec, 0xaa, 0x61, 0x96, 0xa6, 0x5c,
	0x77, 0xc3, 0xa3, 0xc8, 0xda, 0xda, 0x80, 0xd1, 0x21, 0x78, 0x55, 0xfd, 0xa0, 0x0f, 0x61, 0x67,
	0x59, 0x51, 0xb8, 0x26, 0x94, 0x7f, 0xed, 0x98, 0xdf, 0x88, 0xb2, 0xc7, 0xe1, 0xe8, 0xfa, 0x2c,
	0xc9, 0xde, 0x38, 0x26, 0x0d, 0x2e, 0xed, 0x1e, 0xbd, 0xb4, 0xb4, 0xd6, 0x98, 0x75, 0xe6, 0x45,
	0x25, 0x80, 0xfc, 0x0c, 0xb6, 0x5c, 0x49, 0x47, 0x91, 0x1d, 0x8f, 0xb6, 0xa2, 0x06, 0x14, 0xbd,
	0x7a, 0xe6, 0xce, 0x0a, 0xbd, 0xc5, 0x59, 0x81, 0x7e, 0x0f, 0x3b, 0xcb, 0x3a, 0x2f, 0x9e, 0xd0,
	0x37, 0xed, 0x89, 0x80, 0x40, 0xef, 0x45, 0x66, 0x9f, 0xe2, 0xce, 0x7f, 0xc1, 0x19, 0x96, 0xb1,
	0x6e, 0xfd, 0x5f, 0xe0, 0xfc, 0x94, 0xf4, 0xdc, 0x9f, 0x92, 0x83, 0xb7, 0x30, 0x7c, 0x9e, 0xf0,
	0x60, 0x7e, 0xa2, 0xbf, 0x3c, 0xc9, 0x17, 0x30, 0x7a, 0xce, 0x55, 0xf5, 0xfb, 0x48, 0x48, 0xe3,
	0x07, 0x43, 0x0f, 0x57, 0xbb, 0x3b, 0xad, 0x4f, 0x28, 0xfd, 0x5f, 0x45, 0x6f, 0x91, 0x4f, 0x60,
	0xf3, 0x9c, 0xa7, 0x51, 0xfd, 0x05, 0xa5, 0x0b, 0x68, 0xb5, 0xdd, 0xf5, 0x70, 0x6b, 0x7e, 0x81,
	0x6e, 0xed, 0x77, 0x0e, 0xfe, 0xd2, 0x01, 0xd0, 0xaa, 0x0f, 0x67, 0x3c, 0x55, 0xe4, 0x0b, 0xd8,
	0x30, 0x1f, 0x1a, 0x9c, 0x68, 0x05, 0xed, 0xef, 0x9b, 0xdd, 0xbb, 0x2d, 0xa8, 0x7d, 0x82, 0xde,
	0x7a, 0xd8, 0x21, 0x47, 0xd0, 0x37, 0x8f, 0x04, 0xa2, 0x9f, 0xb2, 0x2b, 0x5f, 0x18, 0xbb, 0x1f,
	0xaf, 0x42, 0x97, 0xc2, 0xa6, 0x7d, 0xfd, 0xdd, 0xfb, 0xd9, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xaf, 0x3d, 0x7d, 0x3a, 0x04, 0x16, 0x00, 0x00,
}
